{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.createstockbridge",
    "module": "CreateStockBridge-1.21",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "CreateStockBridge-1.21-0.1.4.jar",
          "url": "CreateStockBridge-1.21-0.1.4.jar",
          "size": 171034,
          "sha512": "ceaf58db777d8e59db4a7d3e724e6be17ccb26db3451aed48a1be4db3642380ad85f587d8628f2b20e3c9de2b6d708b1316c9abb951513c2db4501dad9754414",
          "sha256": "3b95022e5108cbfbc10a3704ce3638c9d53a9e4a35b4423c857bfc58a8033ded",
          "sha1": "c5c8b086422aa85b24c292c27cd9972d4e92f193",
          "md5": "760dc64891a1783dbc02ba64490f4e15"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "the-one-probe-245211",
          "version": {
            "requires": "5502323"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5529595"
          }
        },
        {
          "group": "curse.maven",
          "module": "refined-storage-243076",
          "version": {
            "requires": "6358597"
          }
        },
        {
          "group": "curse.maven",
          "module": "applied-energistics-2-223794",
          "version": {
            "requires": "6225422"
          }
        },
        {
          "group": "curse.maven",
          "module": "guideme-1173950",
          "version": {
            "requires": "6331224"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.4-53"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.21.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.44"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.21.0.247"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.1-11"
          }
        }
      ],
      "files": [
        {
          "name": "CreateStockBridge-1.21-0.1.4.jar",
          "url": "CreateStockBridge-1.21-0.1.4.jar",
          "size": 171034,
          "sha512": "ceaf58db777d8e59db4a7d3e724e6be17ccb26db3451aed48a1be4db3642380ad85f587d8628f2b20e3c9de2b6d708b1316c9abb951513c2db4501dad9754414",
          "sha256": "3b95022e5108cbfbc10a3704ce3638c9d53a9e4a35b4423c857bfc58a8033ded",
          "sha1": "c5c8b086422aa85b24c292c27cd9972d4e92f193",
          "md5": "760dc64891a1783dbc02ba64490f4e15"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "CreateStockBridge-1.21-0.1.4-sources.jar",
          "url": "CreateStockBridge-1.21-0.1.4-sources.jar",
          "size": 124053,
          "sha512": "c2a35447bbe720c5880cba5ba88279b998c30a4c9c2e72b99d5c9a733df1fb370f310dcc0e9075071aed848df7d9fbf7a2ff8865f211d9af2b350fd23e547094",
          "sha256": "fc80744806aa81450b9465b6c0baa094b452ef97185b6f96ed0669ef7cf71e35",
          "sha1": "31ef01b034f0e6a6532e942d948d63e2fde89ac7",
          "md5": "0ef29dcac584c158c6af7b3a34a3704f"
        }
      ]
    }
  ]
}
