{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.toms_storage",
    "module": "TomsStorage-26.1",
    "version": "2.10.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "TomsStorage-26.1-2.10.1.jar",
          "url": "TomsStorage-26.1-2.10.1.jar",
          "size": 860009,
          "sha512": "e11c864e24f5b00b2b83eb3cc032a6a51f20fb49d23f085fc79704421438df64409bf2334816e9f0b44d4f7e73755a3cddd3ea60b4ccdbad559e894abf557c5d",
          "sha256": "a210667a6668469337255ff03fbb0041868a983e7ba4d53238ec4c79e703a403",
          "sha1": "19d746d8765757066ce7cc30e5e906184363e05e",
          "md5": "e7b2b3d45a44291ea8c2bf9cbf304886"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "7817285"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-neoforge",
          "version": {
            "requires": "21.11.814"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-neoforge",
          "version": {
            "requires": "18.0.145"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-neoforge",
          "version": {
            "requires": "16.1.4"
          }
        },
        {
          "group": "curse.maven",
          "module": "polymorph-388800",
          "version": {
            "requires": "5995380"
          }
        },
        {
          "group": "curse.maven",
          "module": "the-one-probe-245211",
          "version": {
            "requires": "5502323"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-26.1.2-neoforge",
          "version": {
            "requires": "29.16.0.48"
          }
        },
        {
          "group": "top.theillusivec4.curios",
          "module": "curios-neoforge",
          "version": {
            "requires": "11.0.1+1.21.5"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-neoforge",
          "version": {
            "requires": "1.1.7+1.21"
          }
        }
      ],
      "files": [
        {
          "name": "TomsStorage-26.1-2.10.1.jar",
          "url": "TomsStorage-26.1-2.10.1.jar",
          "size": 860009,
          "sha512": "e11c864e24f5b00b2b83eb3cc032a6a51f20fb49d23f085fc79704421438df64409bf2334816e9f0b44d4f7e73755a3cddd3ea60b4ccdbad559e894abf557c5d",
          "sha256": "a210667a6668469337255ff03fbb0041868a983e7ba4d53238ec4c79e703a403",
          "sha1": "19d746d8765757066ce7cc30e5e906184363e05e",
          "md5": "e7b2b3d45a44291ea8c2bf9cbf304886"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TomsStorage-26.1-2.10.1-sources.jar",
          "url": "TomsStorage-26.1-2.10.1-sources.jar",
          "size": 552979,
          "sha512": "dd1b7e4245f4fd15ab130f3139436d9ed3817730103a7981c00957ac4970e8a16194545699db3e14a3c99fb182a7d46b8f905bc8b0d5201584b81f65272e703d",
          "sha256": "834706ab86b3e487979daa94211399d0ff1763ff3183d93b5a20d13c4e4f271d",
          "sha1": "2d553c4fc12eb6393e6eab1e95059f0f2859d30a",
          "md5": "af7fa81537ab2b13b889dc07741e436f"
        }
      ]
    },
    {
      "name": "accessTransformerElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "TomsStorage-26.1-2.10.1-access-transformer.cfg",
          "url": "TomsStorage-26.1-2.10.1-access-transformer.cfg",
          "size": 580,
          "sha512": "54fdf56d9dfdaf8bf7935087c6b0b3ced9483c38f324cde64967381ae30892c408f87f00725c13329474d2d1a58ccd4dd7f2fafb1071037842aa0bf6160c75d3",
          "sha256": "654f2b47449578b9ba65586cd2c1b89f128c00ec3c035436dbc714badc6c289a",
          "sha1": "82eb657c2ab86d84fd8f198f4eb64e4df564e315",
          "md5": "1819b5c4f40faba330a37ed08e2432fd"
        }
      ]
    }
  ]
}
