{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.toms_storage",
    "module": "TomsStorage-26.1",
    "version": "2.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "TomsStorage-26.1-2.9.1.jar",
          "url": "TomsStorage-26.1-2.9.1.jar",
          "size": 839808,
          "sha512": "1751e8032e476b574deede5b8c57a669e4caa6ed1ca1df9aca82e0a37dd9994a6e8d20fe6af12b0ccaf728b011c635bf44d2b060a59be4d3e909af3882a3f6bb",
          "sha256": "3c3bb719a722ae5f59cc53450a488e47b6024c5cdd1b6b50c20459b1163982e0",
          "sha1": "904dbc7c2d14b4f592e98d64101085d955885690",
          "md5": "065c8fd2dd434ebe9946b8545f986683"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "7817285"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-neoforge",
          "version": {
            "requires": "21.11.814"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-neoforge",
          "version": {
            "requires": "18.0.145"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-neoforge",
          "version": {
            "requires": "16.1.4"
          }
        },
        {
          "group": "curse.maven",
          "module": "polymorph-388800",
          "version": {
            "requires": "5995380"
          }
        },
        {
          "group": "curse.maven",
          "module": "the-one-probe-245211",
          "version": {
            "requires": "5502323"
          }
        },
        {
          "group": "top.theillusivec4.curios",
          "module": "curios-neoforge",
          "version": {
            "requires": "11.0.1+1.21.5"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-neoforge",
          "version": {
            "requires": "1.1.7+1.21"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.11-neoforge",
          "version": {
            "requires": "27.3.0.14"
          }
        }
      ],
      "files": [
        {
          "name": "TomsStorage-26.1-2.9.1.jar",
          "url": "TomsStorage-26.1-2.9.1.jar",
          "size": 839808,
          "sha512": "1751e8032e476b574deede5b8c57a669e4caa6ed1ca1df9aca82e0a37dd9994a6e8d20fe6af12b0ccaf728b011c635bf44d2b060a59be4d3e909af3882a3f6bb",
          "sha256": "3c3bb719a722ae5f59cc53450a488e47b6024c5cdd1b6b50c20459b1163982e0",
          "sha1": "904dbc7c2d14b4f592e98d64101085d955885690",
          "md5": "065c8fd2dd434ebe9946b8545f986683"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TomsStorage-26.1-2.9.1-sources.jar",
          "url": "TomsStorage-26.1-2.9.1-sources.jar",
          "size": 541629,
          "sha512": "4d465fa268c586d922e6ab6c6d5a11e314dfd47f6fe71cb0603648437e71aa56afd73040c161297d5ba2ab6a3301afdd94a96f88d2cc2ac27fa747f3f6f739f8",
          "sha256": "66bb4390290e7e1752355970b3fb19f180416e3fd1b2acc2973c566c2fbb3777",
          "sha1": "b1746ec62d5b3b881ec3827de0543f890538d7c1",
          "md5": "be86c48b86878b6f4b84fdda04044d51"
        }
      ]
    },
    {
      "name": "accessTransformerElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "TomsStorage-26.1-2.9.1-access-transformer.cfg",
          "url": "TomsStorage-26.1-2.9.1-access-transformer.cfg",
          "size": 580,
          "sha512": "54fdf56d9dfdaf8bf7935087c6b0b3ced9483c38f324cde64967381ae30892c408f87f00725c13329474d2d1a58ccd4dd7f2fafb1071037842aa0bf6160c75d3",
          "sha256": "654f2b47449578b9ba65586cd2c1b89f128c00ec3c035436dbc714badc6c289a",
          "sha1": "82eb657c2ab86d84fd8f198f4eb64e4df564e315",
          "md5": "1819b5c4f40faba330a37ed08e2432fd"
        }
      ]
    }
  ]
}
