{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.createoreexcavation",
    "module": "CreateOreExcavationFabric-1.19",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "8.0.75"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.19.2-common-api",
          "version": {
            "requires": "11.6.0.1013"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.19.2-fabric-api",
          "version": {
            "requires": "11.6.0.1013"
          }
        }
      ],
      "files": [
        {
          "name": "CreateOreExcavationFabric-1.19-1.1.3.jar",
          "url": "CreateOreExcavationFabric-1.19-1.1.3.jar",
          "size": 296148,
          "sha512": "6cc025e11e77c4152fe135a5553058e8f766ac721c299ebdbf35c380a3aba19057e0171fae92766a35e8eaff9f36981d8de0bf22ff61375c50561ee232323bd9",
          "sha256": "5eb741e07ecd03f688ec530d913c50cff06078899cd4c9a7112415e9f0968b91",
          "sha1": "ad9493615edde120a5d5f921b0053f8bcca9e2d5",
          "md5": "0a2e3b0cda7fad544159ed7b2bf853ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "8.0.75"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "forge-config-api-port-fabric-547434",
          "version": {
            "requires": "4143545"
          }
        },
        {
          "group": "com.tom5454.chunkstorage",
          "module": "ChunkStorageFabric-119",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.tterrag.registrate_fabric",
          "module": "Registrate",
          "version": {
            "requires": "1.1.57-MC1.19.2"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "4.0.6"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "6.2.43"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi",
          "version": {
            "requires": "0.7.3+1.19.2"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-fabric-1.19.2",
          "version": {
            "requires": "0.5.0.i-1003+1.19.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "Porting-Lib",
          "version": {
            "requires": "2.1.926+1.19.2"
          }
        },
        {
          "group": "com.jozufozu.flywheel",
          "module": "flywheel-fabric-1.19.2",
          "version": {
            "requires": "0.6.8.a-4"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "1902.6.0-build.142"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "9.1.595"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "me.shedaniel.cloth",
              "module": "*"
            },
            {
              "group": "dev.architectury",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.19.2-fabric",
          "version": {
            "requires": "11.6.0.1013"
          }
        }
      ],
      "files": [
        {
          "name": "CreateOreExcavationFabric-1.19-1.1.3.jar",
          "url": "CreateOreExcavationFabric-1.19-1.1.3.jar",
          "size": 296148,
          "sha512": "6cc025e11e77c4152fe135a5553058e8f766ac721c299ebdbf35c380a3aba19057e0171fae92766a35e8eaff9f36981d8de0bf22ff61375c50561ee232323bd9",
          "sha256": "5eb741e07ecd03f688ec530d913c50cff06078899cd4c9a7112415e9f0968b91",
          "sha1": "ad9493615edde120a5d5f921b0053f8bcca9e2d5",
          "md5": "0a2e3b0cda7fad544159ed7b2bf853ed"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "CreateOreExcavationFabric-1.19-1.1.3-sources.jar",
          "url": "CreateOreExcavationFabric-1.19-1.1.3-sources.jar",
          "size": 149109,
          "sha512": "a2bce359299777fb5a8942d27dd4fbc666cfaffda1a3132e987d2a5af78da405725f5beb05073150af18e7f2b9785a1c04f971baae0bef0df0abd8439bd35347",
          "sha256": "a0d5487d255072fe9cb21b2ce2de911615f569088652299b80ef4b943b7fc4d6",
          "sha1": "a141ffb7af06dcbeb97161d36df14dfa4b02ac53",
          "md5": "ca121685e8bb942ef4896716591ae677"
        }
      ]
    }
  ]
}
