{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.mcp-hybrid-loom",
    "module": "MCPHybridLoom",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "MCPHybridLoom-1.0.0.jar",
          "url": "MCPHybridLoom-1.0.0.jar",
          "size": 10209,
          "sha512": "59e6a560a547be94f07712f38c8cd8d36afa36b1f438b7e54571c4cf80bec525c743d4ca00c16911092db66748a67dc6842d46f77428363b315b6e501a03d7c9",
          "sha256": "e502cdcf85c543042e636e3422cc60d1b97651165d9b9ee2382012c2d115de80",
          "sha1": "2a3105e5c394fd0048bf3a67703d499db5f8fa5d",
          "md5": "99c87e35446418ec2afc1e3bd1d491a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loom",
          "version": {
            "requires": "1.1-SNAPSHOT"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "mapping-io",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "MCPHybridLoom-1.0.0.jar",
          "url": "MCPHybridLoom-1.0.0.jar",
          "size": 10209,
          "sha512": "59e6a560a547be94f07712f38c8cd8d36afa36b1f438b7e54571c4cf80bec525c743d4ca00c16911092db66748a67dc6842d46f77428363b315b6e501a03d7c9",
          "sha256": "e502cdcf85c543042e636e3422cc60d1b97651165d9b9ee2382012c2d115de80",
          "sha1": "2a3105e5c394fd0048bf3a67703d499db5f8fa5d",
          "md5": "99c87e35446418ec2afc1e3bd1d491a8"
        }
      ]
    }
  ]
}
