{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.toms_storage",
    "module": "TomsStorage-26.1",
    "version": "2.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "TomsStorage-26.1-2.9.2.jar",
          "url": "TomsStorage-26.1-2.9.2.jar",
          "size": 852874,
          "sha512": "e974f1cc0086a78d01f022b2bff28fa5308d80e3f8e734c64a34c735651698ff8dc12685d1e71fd72d907d316201eb2e6d2db8295f26b7a4006b07208cde30cc",
          "sha256": "1efc4c3aecfa9a5370257f195fc83514288b83c2056de58b0da0d4d8355e1222",
          "sha1": "8e1ec8ea4d934c4ddd91ea5ded02146e8e0d1406",
          "md5": "a257ff2d783e8f94bd6c2cc14a4c866c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "7817285"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-neoforge",
          "version": {
            "requires": "21.11.814"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-neoforge",
          "version": {
            "requires": "18.0.145"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-neoforge",
          "version": {
            "requires": "16.1.4"
          }
        },
        {
          "group": "curse.maven",
          "module": "polymorph-388800",
          "version": {
            "requires": "5995380"
          }
        },
        {
          "group": "curse.maven",
          "module": "the-one-probe-245211",
          "version": {
            "requires": "5502323"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-26.1.1-neoforge",
          "version": {
            "requires": "29.4.0.23"
          }
        },
        {
          "group": "top.theillusivec4.curios",
          "module": "curios-neoforge",
          "version": {
            "requires": "11.0.1+1.21.5"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-neoforge",
          "version": {
            "requires": "1.1.7+1.21"
          }
        }
      ],
      "files": [
        {
          "name": "TomsStorage-26.1-2.9.2.jar",
          "url": "TomsStorage-26.1-2.9.2.jar",
          "size": 852874,
          "sha512": "e974f1cc0086a78d01f022b2bff28fa5308d80e3f8e734c64a34c735651698ff8dc12685d1e71fd72d907d316201eb2e6d2db8295f26b7a4006b07208cde30cc",
          "sha256": "1efc4c3aecfa9a5370257f195fc83514288b83c2056de58b0da0d4d8355e1222",
          "sha1": "8e1ec8ea4d934c4ddd91ea5ded02146e8e0d1406",
          "md5": "a257ff2d783e8f94bd6c2cc14a4c866c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TomsStorage-26.1-2.9.2-sources.jar",
          "url": "TomsStorage-26.1-2.9.2-sources.jar",
          "size": 545667,
          "sha512": "87a99bc359ada3f47f6f6cccddba8addfbabdd687c7d38850793295fb791e037216f8d83bd618336088fd668b21e9f5b408ea00cf0ea12ade3bcf4442f332db0",
          "sha256": "c14deff65c7bd0d37a379a1d3261c4adc55cf7ed6bb003c2dd455fcf843c7c3e",
          "sha1": "41dde423ffa2739b1aa28b50c7bbe7eaac60710c",
          "md5": "b1c22ff8f3a66fdf8f7bb2eac36bc5de"
        }
      ]
    },
    {
      "name": "accessTransformerElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "TomsStorage-26.1-2.9.2-access-transformer.cfg",
          "url": "TomsStorage-26.1-2.9.2-access-transformer.cfg",
          "size": 580,
          "sha512": "54fdf56d9dfdaf8bf7935087c6b0b3ced9483c38f324cde64967381ae30892c408f87f00725c13329474d2d1a58ccd4dd7f2fafb1071037842aa0bf6160c75d3",
          "sha256": "654f2b47449578b9ba65586cd2c1b89f128c00ec3c035436dbc714badc6c289a",
          "sha1": "82eb657c2ab86d84fd8f198f4eb64e4df564e315",
          "md5": "1819b5c4f40faba330a37ed08e2432fd"
        }
      ]
    }
  ]
}
