{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.toms_storage",
    "module": "TomsStorage-26.3",
    "version": "2.12.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "TomsStorage-26.3-2.12.2.jar",
          "url": "TomsStorage-26.3-2.12.2.jar",
          "size": 858689,
          "sha512": "8dbcca2da36a1948aa36ce40d2109488fbe31d82519cf9b42df54d7029152525c0ddf2437a140731f2e63c5176f54550f26bb6cfa439ccdde45ea88b29135024",
          "sha256": "84a7c65d5af216c7eb504ed5a9eda767dd0176cb3ee47522a839d489b894ed31",
          "sha1": "7cbc83ed93ebe8959dbaf448f0250ea216bdc0e0",
          "md5": "5ca2e28d5c43d7a7246354a952bfbe25"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.neoforged",
          "module": "neoforge",
          "version": {
            "requires": "26.3.0.39-beta"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "8892782"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-neoforge",
          "version": {
            "requires": "21.11.814"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-neoforge",
          "version": {
            "requires": "18.0.145"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-neoforge",
          "version": {
            "requires": "16.1.4"
          }
        },
        {
          "group": "curse.maven",
          "module": "polymorph-388800",
          "version": {
            "requires": "5995380"
          }
        },
        {
          "group": "curse.maven",
          "module": "the-one-probe-245211",
          "version": {
            "requires": "5502323"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-26.3-neoforge",
          "version": {
            "requires": "31.6.0.25"
          }
        },
        {
          "group": "top.theillusivec4.curios",
          "module": "curios-neoforge",
          "version": {
            "requires": "11.0.1+1.21.5"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-neoforge",
          "version": {
            "requires": "1.1.7+1.21"
          }
        }
      ],
      "files": [
        {
          "name": "TomsStorage-26.3-2.12.2.jar",
          "url": "TomsStorage-26.3-2.12.2.jar",
          "size": 858689,
          "sha512": "8dbcca2da36a1948aa36ce40d2109488fbe31d82519cf9b42df54d7029152525c0ddf2437a140731f2e63c5176f54550f26bb6cfa439ccdde45ea88b29135024",
          "sha256": "84a7c65d5af216c7eb504ed5a9eda767dd0176cb3ee47522a839d489b894ed31",
          "sha1": "7cbc83ed93ebe8959dbaf448f0250ea216bdc0e0",
          "md5": "5ca2e28d5c43d7a7246354a952bfbe25"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TomsStorage-26.3-2.12.2-sources.jar",
          "url": "TomsStorage-26.3-2.12.2-sources.jar",
          "size": 552878,
          "sha512": "136ce4185d6af03454096d039bfb31aec535657fa0e3ed7799cda2d42f070cf86cbc45fc2dd95a22fbef839c84b6c831b00e1e4f68147ddec944433afc6ce753",
          "sha256": "04f9d12b2126d9261072c8050317bb5849328f4bb3f6a3b9c32797f9cb02130b",
          "sha1": "0d219d7ebfe548c8940085a3d76b3259a45bc12d",
          "md5": "150de577e7303dfc02cd2101a24297fe"
        }
      ]
    }
  ]
}
