{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.aerocables",
    "module": "AeroCables",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "AeroCables-0.1.0.jar",
          "url": "AeroCables-0.1.0.jar",
          "size": 143611,
          "sha512": "0be88999441ec3be1a36a45b9f100a2cc417886b79f46d0173d4609c19f85e22dfb18641efffb58f531a8605f5abc2dc62694619d73b760b04107b1f999f0f05",
          "sha256": "2a75ccf9c0f5e4363e44779bdc759559c91d2d0d17a494aa81cb8ab471d082f8",
          "sha1": "3b07ecb6f43ba5291257aea7ed6b9414d5cde9fb",
          "md5": "bb3fdd866ce7c9f072e0d039549eb4c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.9-215"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.21.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "ponder-neoforge",
          "version": {
            "requires": "1.0.81+mc1.21.1"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+67"
          }
        },
        {
          "group": "com.tom5454.cpm",
          "module": "CustomPlayerModels-1.21",
          "version": {
            "requires": "0.6.25a"
          }
        },
        {
          "group": "com.tom5454.toms_storage",
          "module": "TomsStorage-121",
          "version": {
            "requires": "2.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6011258"
          }
        },
        {
          "group": "dev.ryanhcode.sable",
          "module": "sable-neoforge-1.21.1",
          "version": {
            "requires": "[1.0.3,)"
          }
        },
        {
          "group": "dev.eriksonn.aeronautics",
          "module": "aeronautics-neoforge-1.21.1",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.simulated_team.simulated",
          "module": "simulated-neoforge-1.21.1",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "integrated-dynamics-236307",
          "version": {
            "requires": "7648811"
          }
        },
        {
          "group": "curse.maven",
          "module": "cyclops-core-232758",
          "version": {
            "requires": "7637998"
          }
        },
        {
          "group": "curse.maven",
          "module": "common-capabilities-247007",
          "version": {
            "requires": "7361876"
          }
        },
        {
          "group": "curse.maven",
          "module": "refined-storage-243076",
          "version": {
            "requires": "7610477"
          }
        },
        {
          "group": "curse.maven",
          "module": "applied-energistics-2-223794",
          "version": {
            "requires": "7027323"
          }
        },
        {
          "group": "curse.maven",
          "module": "guideme-1173950",
          "version": {
            "requires": "7127444"
          }
        },
        {
          "group": "curse.maven",
          "module": "mekanism-268560",
          "version": {
            "requires": "7904058"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.21.2.313"
          }
        },
        {
          "group": "dev.ryanhcode.offroad",
          "module": "offroad-neoforge-1.21.1",
          "version": {
            "requires": "1.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "AeroCables-0.1.0.jar",
          "url": "AeroCables-0.1.0.jar",
          "size": 143611,
          "sha512": "0be88999441ec3be1a36a45b9f100a2cc417886b79f46d0173d4609c19f85e22dfb18641efffb58f531a8605f5abc2dc62694619d73b760b04107b1f999f0f05",
          "sha256": "2a75ccf9c0f5e4363e44779bdc759559c91d2d0d17a494aa81cb8ab471d082f8",
          "sha1": "3b07ecb6f43ba5291257aea7ed6b9414d5cde9fb",
          "md5": "bb3fdd866ce7c9f072e0d039549eb4c6"
        }
      ]
    }
  ]
}
