{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.toms_trading",
    "module": "TomsTradingNetworkFabric-121",
    "version": "0.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.21-common-api",
          "version": {
            "requires": "19.5.0.31"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21-fabric-api",
          "version": {
            "requires": "19.5.0.31"
          }
        }
      ],
      "files": [
        {
          "name": "TomsTradingNetworkFabric-121-0.3.2.jar",
          "url": "TomsTradingNetworkFabric-121-0.3.2.jar",
          "size": 262570,
          "sha512": "9c8dd903593d8d3a6ceeccb0ccbd146a44bbcd487bb1ed0f7c34471a4f00d73dc20599f852b2f511dbc6196073bb162bea13e91bccd57f5e20bf405dfd774d73",
          "sha256": "3db00260ed9c62ef3b20ab94245f48c5410b6e9cf5abc1acf6ff7af7d5be13ac",
          "sha1": "87374d6b0062b80dedd94288113cc8bc2a4a0573",
          "md5": "77c38e23660079bebefc740cc40b53d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.0+1.21.1"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "13.0.4"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5493289"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "16.0.729"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "dev.architectury",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21-fabric",
          "version": {
            "requires": "19.5.0.31"
          }
        }
      ],
      "files": [
        {
          "name": "TomsTradingNetworkFabric-121-0.3.2.jar",
          "url": "TomsTradingNetworkFabric-121-0.3.2.jar",
          "size": 262570,
          "sha512": "9c8dd903593d8d3a6ceeccb0ccbd146a44bbcd487bb1ed0f7c34471a4f00d73dc20599f852b2f511dbc6196073bb162bea13e91bccd57f5e20bf405dfd774d73",
          "sha256": "3db00260ed9c62ef3b20ab94245f48c5410b6e9cf5abc1acf6ff7af7d5be13ac",
          "sha1": "87374d6b0062b80dedd94288113cc8bc2a4a0573",
          "md5": "77c38e23660079bebefc740cc40b53d7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TomsTradingNetworkFabric-121-0.3.2-sources.jar",
          "url": "TomsTradingNetworkFabric-121-0.3.2-sources.jar",
          "size": 203224,
          "sha512": "33acb520f2c2275ab1452ed39a3b92d92f2d80ff4aa0fdc9523d0cea7c5e0cc9519de084e751c655f76eb9cd0227390bf4dbc85572756409e9c5618c9dded96e",
          "sha256": "adc0cd64b0df5483c4f925fed609c7144570edd4ecc40391777540c665030e8a",
          "sha1": "a3d9b5f07054661dc6084949b8b613c8e3f460cc",
          "md5": "900a02b2d644b6b8cde4bc1b9e0d30c1"
        }
      ]
    }
  ]
}
