{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.toms_storage",
    "module": "TomsStorage-1.21.8",
    "version": "2.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "TomsStorage-1.21.8-2.5.1.jar",
          "url": "TomsStorage-1.21.8-2.5.1.jar",
          "size": 848191,
          "sha512": "c156e04e9f4cb6825fcee8d8dcc2fec8da90ffc97c109f285cbf16dd570ee4f6213a385e807701eb05fa6e713cd6eca98f34db0154cb03c81fa185cbdc413730",
          "sha256": "ba4dc7bea6b14ff8de05cb0d085bbb91838e5a12ca530c89300137e0e02c82f1",
          "sha1": "e453bf185edad1242066519ce751ad1dafb550ee",
          "md5": "776e54a607e7ad9527c7738058cf4594"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6669809"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-neoforge",
          "version": {
            "requires": "19.0.806"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-neoforge",
          "version": {
            "requires": "18.0.145"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-neoforge",
          "version": {
            "requires": "16.1.4"
          }
        },
        {
          "group": "curse.maven",
          "module": "polymorph-388800",
          "version": {
            "requires": "5995380"
          }
        },
        {
          "group": "curse.maven",
          "module": "the-one-probe-245211",
          "version": {
            "requires": "5502323"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.5-neoforge",
          "version": {
            "requires": "21.3.2.22"
          }
        },
        {
          "group": "top.theillusivec4.curios",
          "module": "curios-neoforge",
          "version": {
            "requires": "11.0.1+1.21.5"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-neoforge",
          "version": {
            "requires": "1.1.7+1.21"
          }
        }
      ],
      "files": [
        {
          "name": "TomsStorage-1.21.8-2.5.1.jar",
          "url": "TomsStorage-1.21.8-2.5.1.jar",
          "size": 848191,
          "sha512": "c156e04e9f4cb6825fcee8d8dcc2fec8da90ffc97c109f285cbf16dd570ee4f6213a385e807701eb05fa6e713cd6eca98f34db0154cb03c81fa185cbdc413730",
          "sha256": "ba4dc7bea6b14ff8de05cb0d085bbb91838e5a12ca530c89300137e0e02c82f1",
          "sha1": "e453bf185edad1242066519ce751ad1dafb550ee",
          "md5": "776e54a607e7ad9527c7738058cf4594"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TomsStorage-1.21.8-2.5.1-sources.jar",
          "url": "TomsStorage-1.21.8-2.5.1-sources.jar",
          "size": 543018,
          "sha512": "edac4ed73131b1b64d7399298124008a33b8d9e96ec881d3cac2e37b2a8f101610e2e64ac11cf15d7f4639813770870ecd64c7a07600bd8b3889e3c7223aff9e",
          "sha256": "5de768bb734dd70b1011c4920df2244fbdbd2edd74d93563e3ce8229152f7678",
          "sha1": "f9e3bce45a75d2046efee92f9c8595e1a9811b1c",
          "md5": "ff28a9145264bf34353eaca56fb3e4ef"
        }
      ]
    }
  ]
}
