{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.createoreexcavation",
    "module": "CreateOreExcavationFabric-1.20",
    "version": "1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "11.1.106"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "info.journeymap",
          "module": "journeymap-api",
          "version": {
            "requires": "1.20-1.9-fabric-SNAPSHOT"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.22"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.22"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "CreateOreExcavationFabric-1.20-1.4.1.jar",
          "url": "CreateOreExcavationFabric-1.20-1.4.1.jar",
          "size": 380925,
          "sha512": "0c282a37c2b9afcce86355e788c8699e83569a52d6a42a36bb0ca94048c39ec98f791eebc4e426e5d5fe4e06b54af5d8c754373ba85a8dca8c3a3c7504a11ac4",
          "sha256": "38b5d4e4a428d350639b80dff5d0556cf87248cbfd2d972565bf7eed9b7ec8f9",
          "sha1": "47d95594370e2887ad82290bfe1de87fd5621ae8",
          "md5": "8479139b5ca0d3965619477c9273dd95"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "11.1.106"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "info.journeymap",
          "module": "journeymap-api",
          "version": {
            "requires": "1.20-1.9-fabric-SNAPSHOT"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.87.0+1.20.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "forge-config-api-port-fabric-547434",
          "version": {
            "requires": "4583000"
          }
        },
        {
          "group": "com.tom5454.chunkstorage",
          "module": "ChunkStorageFabric-120",
          "version": {
            "requires": "1.0.3"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.tterrag.registrate_fabric",
          "module": "Registrate",
          "version": {
            "requires": "1.3.62-MC1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc",
              "module": "*"
            },
            {
              "group": "io.github.fabricators_of_create",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-fabric-1.20.1",
          "version": {
            "requires": "0.5.1-d-build.1161+mc1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "Porting-Lib",
          "version": {
            "requires": "2.1.1127+1.20"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.jozufozu.flywheel",
          "module": "flywheel-fabric-1.20.1",
          "version": {
            "requires": "0.6.9-1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.3-build.45"
          }
        },
        {
          "group": "curse.maven",
          "module": "journeymap-32274",
          "version": {
            "requires": "4841232"
          }
        }
      ],
      "files": [
        {
          "name": "CreateOreExcavationFabric-1.20-1.4.1.jar",
          "url": "CreateOreExcavationFabric-1.20-1.4.1.jar",
          "size": 380925,
          "sha512": "0c282a37c2b9afcce86355e788c8699e83569a52d6a42a36bb0ca94048c39ec98f791eebc4e426e5d5fe4e06b54af5d8c754373ba85a8dca8c3a3c7504a11ac4",
          "sha256": "38b5d4e4a428d350639b80dff5d0556cf87248cbfd2d972565bf7eed9b7ec8f9",
          "sha1": "47d95594370e2887ad82290bfe1de87fd5621ae8",
          "md5": "8479139b5ca0d3965619477c9273dd95"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "CreateOreExcavationFabric-1.20-1.4.1-sources.jar",
          "url": "CreateOreExcavationFabric-1.20-1.4.1-sources.jar",
          "size": 197120,
          "sha512": "e33c4e2bbd8554ec88a1c37598d6fd40a3d2bb2446500c8a101f57deb46d75762da72fa5a079b5e1a5f3ca7a59961846d7417da9e0115571b7b3f81e765fca9d",
          "sha256": "9fe87505646b9ef3eac69c2d424dcf2c79d3318907fa3568fc72906cd9034567",
          "sha1": "bc03724df52b3142c7a972f3f1009549ca302f82",
          "md5": "4f102556d2e22e136ed8d3eca73ad74d"
        }
      ]
    }
  ]
}
