{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.createstockbridge",
    "module": "CreateStockBridge-1.21",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "CreateStockBridge-1.21-0.2.0.jar",
          "url": "CreateStockBridge-1.21-0.2.0.jar",
          "size": 180413,
          "sha512": "5c5bc8c077a2eb80fb7625f982c7ce77c79fd0db14b02f880fe66946863af7cf493d502497a74d9d9507d2402fb98f701b0a43cf29989850f3ca24274d4e3c36",
          "sha256": "e1ac644064fb9276d4aa529c2c3ff67ec4eb0e87b06f27f4c7cfeb1f38a0a613",
          "sha1": "ff4d5af507ee2275d17dbc1d31b7615ce159c919",
          "md5": "bf72f898430bb9d163e040e58ffff074"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "the-one-probe-245211",
          "version": {
            "requires": "5502323"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5529595"
          }
        },
        {
          "group": "curse.maven",
          "module": "refined-storage-243076",
          "version": {
            "requires": "7039043"
          }
        },
        {
          "group": "curse.maven",
          "module": "applied-energistics-2-223794",
          "version": {
            "requires": "7027323"
          }
        },
        {
          "group": "curse.maven",
          "module": "guideme-1173950",
          "version": {
            "requires": "7127444"
          }
        },
        {
          "group": "curse.maven",
          "module": "ae2-jei-integration-1074338",
          "version": {
            "requires": "5748513"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.9-215"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.21.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "ponder-neoforge",
          "version": {
            "requires": "1.0.81+mc1.21.1"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+67"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.21.0.247"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "CreateStockBridge-1.21-0.2.0.jar",
          "url": "CreateStockBridge-1.21-0.2.0.jar",
          "size": 180413,
          "sha512": "5c5bc8c077a2eb80fb7625f982c7ce77c79fd0db14b02f880fe66946863af7cf493d502497a74d9d9507d2402fb98f701b0a43cf29989850f3ca24274d4e3c36",
          "sha256": "e1ac644064fb9276d4aa529c2c3ff67ec4eb0e87b06f27f4c7cfeb1f38a0a613",
          "sha1": "ff4d5af507ee2275d17dbc1d31b7615ce159c919",
          "md5": "bf72f898430bb9d163e040e58ffff074"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "CreateStockBridge-1.21-0.2.0-sources.jar",
          "url": "CreateStockBridge-1.21-0.2.0-sources.jar",
          "size": 128689,
          "sha512": "d4e16dc4840997e8fd933b4a10a54cf57a86477c8650fc145754a40b671b917189e1b9f38f3363d334db66632a0d5c51f4f7449e3369b543b15f566d9678cba2",
          "sha256": "9cc4e27da6d75fd96b0b89a4e930a0a294d643e12030ac8df02e8eff2d02f2dd",
          "sha1": "28fa7b043237ef4745fbfc8b4adb60e56f576233",
          "md5": "5cf278ff68008a90a36f6077d2cfa6cf"
        }
      ]
    }
  ]
}
