{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.more-immersive-wires",
    "module": "MoreImmersiveWires-121",
    "version": "1.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "MoreImmersiveWires-121-1.1.7.jar",
          "url": "MoreImmersiveWires-121-1.1.7.jar",
          "size": 219031,
          "sha512": "41b187e2f635f14a1e1b6338d330ee2e571ca0910d74d600ec637e04a67203056b0c5d4103bc9b93a5608235d09b0ec67bd50ba82e7ce7eaef53e1cd676b8d0d",
          "sha256": "f358702a99c81204240bfb6d178d5696b8940f91558c792758c083518d66a701",
          "sha1": "ff2c3fc5e762da770d87940577b3b4fd162a9e6c",
          "md5": "a400dc901746064ff48e4def360f883d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "the-one-probe-245211",
          "version": {
            "requires": "5502323"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5529595"
          }
        },
        {
          "group": "curse.maven",
          "module": "immersive-engineering-231951",
          "version": {
            "requires": "6235316"
          }
        },
        {
          "group": "curse.maven",
          "module": "refined-storage-243076",
          "version": {
            "requires": "6358597"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "cc-tweaked",
          "version": {
            "requires": "h6qYZ1UT"
          }
        },
        {
          "group": "curse.maven",
          "module": "applied-energistics-2-223794",
          "version": {
            "requires": "6225422"
          }
        },
        {
          "group": "curse.maven",
          "module": "guideme-1173950",
          "version": {
            "requires": "6331224"
          }
        },
        {
          "group": "malte0811",
          "module": "BlockModelSplitter",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "malte0811",
          "module": "DualCodecs",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "integrated-dynamics-236307",
          "version": {
            "requires": "6001774"
          }
        },
        {
          "group": "curse.maven",
          "module": "cyclops-core-232758",
          "version": {
            "requires": "5979361"
          }
        },
        {
          "group": "curse.maven",
          "module": "common-capabilities-247007",
          "version": {
            "requires": "5992581"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.21.0.247"
          }
        }
      ],
      "files": [
        {
          "name": "MoreImmersiveWires-121-1.1.7.jar",
          "url": "MoreImmersiveWires-121-1.1.7.jar",
          "size": 219031,
          "sha512": "41b187e2f635f14a1e1b6338d330ee2e571ca0910d74d600ec637e04a67203056b0c5d4103bc9b93a5608235d09b0ec67bd50ba82e7ce7eaef53e1cd676b8d0d",
          "sha256": "f358702a99c81204240bfb6d178d5696b8940f91558c792758c083518d66a701",
          "sha1": "ff2c3fc5e762da770d87940577b3b4fd162a9e6c",
          "md5": "a400dc901746064ff48e4def360f883d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "MoreImmersiveWires-121-1.1.7-sources.jar",
          "url": "MoreImmersiveWires-121-1.1.7-sources.jar",
          "size": 156468,
          "sha512": "3c11a05364d10a90e1b8842434abc168f828edf5779d17c59db0737666f3d000c136bc1a251fca0f579014d9a8948b4c468aba18be678a7403de73df70a302ad",
          "sha256": "fdca218c8be33e73f848b90f3537ab905cb63e5cbf24e6476da33e5b5f2b854b",
          "sha1": "ec21c1f67a020ab1a3f8a9d1f3bf2f5c69a95b09",
          "md5": "082be66a1149a70864bc88b5a4547ee4"
        }
      ]
    }
  ]
}
