{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.createstockbridge",
    "module": "CreateStockBridge-1.21",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "CreateStockBridge-1.21-0.1.3.jar",
          "url": "CreateStockBridge-1.21-0.1.3.jar",
          "size": 171034,
          "sha512": "fa75b275dfdb0bc23c4df91e414a3adfde118071dae13f47a39ac65198e0e61e68a8e1f5179ec5c59a64833cea2d2317e7cd8a11713bfc6e52f78aabcdb86a40",
          "sha256": "fc06b01f448d67659255c6c1b213377cdbe5f71a50651ff435589c35d46d0739",
          "sha1": "909667c9e539829d6cb3d8ddacf8c7ca8acc9696",
          "md5": "af13de5d21f799be6a4f58a53e9c38ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "the-one-probe-245211",
          "version": {
            "requires": "5502323"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5529595"
          }
        },
        {
          "group": "curse.maven",
          "module": "refined-storage-243076",
          "version": {
            "requires": "6358597"
          }
        },
        {
          "group": "curse.maven",
          "module": "applied-energistics-2-223794",
          "version": {
            "requires": "6225422"
          }
        },
        {
          "group": "curse.maven",
          "module": "guideme-1173950",
          "version": {
            "requires": "6331224"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.4-53"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.21.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.44"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.21.0.247"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.1-11"
          }
        }
      ],
      "files": [
        {
          "name": "CreateStockBridge-1.21-0.1.3.jar",
          "url": "CreateStockBridge-1.21-0.1.3.jar",
          "size": 171034,
          "sha512": "fa75b275dfdb0bc23c4df91e414a3adfde118071dae13f47a39ac65198e0e61e68a8e1f5179ec5c59a64833cea2d2317e7cd8a11713bfc6e52f78aabcdb86a40",
          "sha256": "fc06b01f448d67659255c6c1b213377cdbe5f71a50651ff435589c35d46d0739",
          "sha1": "909667c9e539829d6cb3d8ddacf8c7ca8acc9696",
          "md5": "af13de5d21f799be6a4f58a53e9c38ea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "CreateStockBridge-1.21-0.1.3-sources.jar",
          "url": "CreateStockBridge-1.21-0.1.3-sources.jar",
          "size": 124053,
          "sha512": "22035fa759a4c2c1e2d80a6475d49d586afba1d526797cfd62ac96e004f55ae9073e636d54733ea380085b581ad53576c8abe650439adbfc629a95f04a2e27d3",
          "sha256": "ee9bf052ca2d81bceb08171da531409aaad5453266399307b89c8e539d49e359",
          "sha1": "28d8e5b692553a1eb270922c06318ddb573eb601",
          "md5": "7f57e9a5d525943fcf5e1c6cdf3034dc"
        }
      ]
    }
  ]
}
