{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.toms_storage",
    "module": "TomsStorage-121",
    "version": "2.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "TomsStorage-121-2.1.3.jar",
          "url": "TomsStorage-121-2.1.3.jar",
          "size": 823522,
          "sha512": "d1b841307ec2d5af2f0e4e840a01a30d347e8aa02189865c689b0560158aea961fbc96bca21fba44dddc05df6dfc49697971014ce9f8d782208c8de239deeac3",
          "sha256": "e22c92ca5042bbf5705782e6bdd7ba5770bb5faf3100edced7f4df37c6789395",
          "sha1": "83a41a2d51250082f27dc8e6c96d00668dfa25d4",
          "md5": "9c7435c06699693493cf84b958c127b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-neoforge",
          "version": {
            "requires": "16.0.799"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-neoforge",
          "version": {
            "requires": "15.0.140"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-neoforge",
          "version": {
            "requires": "13.0.8"
          }
        },
        {
          "group": "curse.maven",
          "module": "polymorph-388800",
          "version": {
            "requires": "5995380"
          }
        },
        {
          "group": "curse.maven",
          "module": "the-one-probe-245211",
          "version": {
            "requires": "5502323"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5529595"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.21.0.247"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-neoforge",
          "version": {
            "requires": "1.1.19+1.21.1"
          }
        },
        {
          "group": "top.theillusivec4.curios",
          "module": "curios-neoforge",
          "version": {
            "requires": "9.4.0+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "TomsStorage-121-2.1.3.jar",
          "url": "TomsStorage-121-2.1.3.jar",
          "size": 823522,
          "sha512": "d1b841307ec2d5af2f0e4e840a01a30d347e8aa02189865c689b0560158aea961fbc96bca21fba44dddc05df6dfc49697971014ce9f8d782208c8de239deeac3",
          "sha256": "e22c92ca5042bbf5705782e6bdd7ba5770bb5faf3100edced7f4df37c6789395",
          "sha1": "83a41a2d51250082f27dc8e6c96d00668dfa25d4",
          "md5": "9c7435c06699693493cf84b958c127b1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TomsStorage-121-2.1.3-sources.jar",
          "url": "TomsStorage-121-2.1.3-sources.jar",
          "size": 533144,
          "sha512": "6eca9dc3d129b4cc5a50bd5620e0e4b33bbaaf617090acb3e40b0e9060a2e8e69d868117512017bad9c503b0a28cedfa043f7dd147082e2499eb0a3051d2a146",
          "sha256": "875208993ad2e4352444e627266c8b7537518771981d1c89c67e12fb3a4957fb",
          "sha1": "1f54a93d672e26a50c5d063dce1b66e1b2a5df2c",
          "md5": "a778f4a62ca1acbf710d40a27df55530"
        }
      ]
    }
  ]
}
