{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.createoreexcavation",
    "module": "CreateOreExcavationFabric-1.19",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "8.0.75"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.19.2-common-api",
          "version": {
            "requires": "11.6.0.1013"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.19.2-fabric-api",
          "version": {
            "requires": "11.6.0.1013"
          }
        }
      ],
      "files": [
        {
          "name": "CreateOreExcavationFabric-1.19-1.1.2.jar",
          "url": "CreateOreExcavationFabric-1.19-1.1.2.jar",
          "size": 295901,
          "sha512": "470bbb00591e382e6d5ec6c6b1931225538557139bbbab4f317f3ccdbdcd4ba8281a34412a0eb2d27352e0fc416df7a29232cba02ff86e700db8f85e1fef27b1",
          "sha256": "c29691b3e8da856fbc1384acdd15e2998d148675a84a3a523077498d63135d67",
          "sha1": "911913233b1fefb9d35f337875ca1ff7224137c6",
          "md5": "bd29514285dc666cb72fcdbe157f8852"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "8.0.75"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.14"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "forge-config-api-port-fabric-547434",
          "version": {
            "requires": "4401535"
          }
        },
        {
          "group": "com.tom5454.chunkstorage",
          "module": "ChunkStorageFabric-119",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.tterrag.registrate_fabric",
          "module": "Registrate",
          "version": {
            "requires": "1.1.50-MC1.19.2"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "4.0.6"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "6.2.43"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi",
          "version": {
            "requires": "0.6.3+1.19.2"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-fabric-1.19.2",
          "version": {
            "requires": "0.5.0.i-946+1.19.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "porting-lib",
          "version": {
            "requires": "2.1.811+1.19.2"
          }
        },
        {
          "group": "com.jozufozu.flywheel",
          "module": "flywheel-fabric-1.19.2",
          "version": {
            "requires": "0.6.8.a-4"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "1902.6.0-build.142"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "9.1.595"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "me.shedaniel.cloth",
              "module": "*"
            },
            {
              "group": "dev.architectury",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.19.2-fabric",
          "version": {
            "requires": "11.6.0.1013"
          }
        }
      ],
      "files": [
        {
          "name": "CreateOreExcavationFabric-1.19-1.1.2.jar",
          "url": "CreateOreExcavationFabric-1.19-1.1.2.jar",
          "size": 295901,
          "sha512": "470bbb00591e382e6d5ec6c6b1931225538557139bbbab4f317f3ccdbdcd4ba8281a34412a0eb2d27352e0fc416df7a29232cba02ff86e700db8f85e1fef27b1",
          "sha256": "c29691b3e8da856fbc1384acdd15e2998d148675a84a3a523077498d63135d67",
          "sha1": "911913233b1fefb9d35f337875ca1ff7224137c6",
          "md5": "bd29514285dc666cb72fcdbe157f8852"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "CreateOreExcavationFabric-1.19-1.1.2-sources.jar",
          "url": "CreateOreExcavationFabric-1.19-1.1.2-sources.jar",
          "size": 148939,
          "sha512": "6d016c2bdc358a47b0e7ef426e59a5ea6134d53c1d2c848d391f43357b6674a22bc0cef3416a46fd872fe6c3e7078f9a09b2956c83e40a40ec3ab7c90de9e74b",
          "sha256": "eedc4492319206c3556731b88bf3e361db1ac08e6223694a6311fb597db56bca",
          "sha1": "33d9a3e29c32da9d67e5c6cd3b9c1aec7122e170",
          "md5": "692235f22c59ac62ae7206e82be39c2b"
        }
      ]
    }
  ]
}
