{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.toms_storage",
    "module": "TomsStorage-121",
    "version": "2.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "TomsStorage-121-2.2.0.jar",
          "url": "TomsStorage-121-2.2.0.jar",
          "size": 829300,
          "sha512": "c4236460268c6c1f297ae0bc8ca5a5cccd836fc07055c1b6cf9e8f5da45f7602bf1d10354c6ca77abf8260c5f8b6e9dbdbd1426860564acba7195e5ea041a37f",
          "sha256": "8e92ebb711cefe7e83cc670f09e18ffcab37641c1cc9b650131c252639444932",
          "sha1": "36b9795cc1991596308dff6483a6b45c2fd8e293",
          "md5": "19169abb0ea41e0aa0cfe0ca8ef3dbbe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-neoforge",
          "version": {
            "requires": "16.0.799"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-neoforge",
          "version": {
            "requires": "15.0.140"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-neoforge",
          "version": {
            "requires": "13.0.8"
          }
        },
        {
          "group": "curse.maven",
          "module": "polymorph-388800",
          "version": {
            "requires": "5995380"
          }
        },
        {
          "group": "curse.maven",
          "module": "the-one-probe-245211",
          "version": {
            "requires": "5502323"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5529595"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.21.0.247"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-neoforge",
          "version": {
            "requires": "1.1.19+1.21.1"
          }
        },
        {
          "group": "top.theillusivec4.curios",
          "module": "curios-neoforge",
          "version": {
            "requires": "9.4.0+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "TomsStorage-121-2.2.0.jar",
          "url": "TomsStorage-121-2.2.0.jar",
          "size": 829300,
          "sha512": "c4236460268c6c1f297ae0bc8ca5a5cccd836fc07055c1b6cf9e8f5da45f7602bf1d10354c6ca77abf8260c5f8b6e9dbdbd1426860564acba7195e5ea041a37f",
          "sha256": "8e92ebb711cefe7e83cc670f09e18ffcab37641c1cc9b650131c252639444932",
          "sha1": "36b9795cc1991596308dff6483a6b45c2fd8e293",
          "md5": "19169abb0ea41e0aa0cfe0ca8ef3dbbe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TomsStorage-121-2.2.0-sources.jar",
          "url": "TomsStorage-121-2.2.0-sources.jar",
          "size": 535304,
          "sha512": "be2e4706cb65255ab1e2e257cdfe8a852d7c5069f0122c86202c77e3af83d8129703b0e65dbfdabbc0fa52a431415278602f8395e09b5571f21f6f9490b8ca9c",
          "sha256": "be5137be9a3e6f46dcc7db00e347437f7f02691e2540ff0207160ff6e82e51ff",
          "sha1": "b7f39b5102aeb1b5ca54ed2087ab96652b5bdf50",
          "md5": "61212a980ee7989b9d3cce418ff5fcfe"
        }
      ]
    }
  ]
}
