{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.createoreexcavation",
    "module": "CreateOreExcavationFabric-1.20",
    "version": "1.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "11.1.106"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "accessors",
          "version": {
            "requires": "2.3.2+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "2.3.2+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "2.3.2+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "extensions",
          "version": {
            "requires": "2.3.2+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "networking",
          "version": {
            "requires": "2.3.2+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "obj_loader",
          "version": {
            "requires": "2.3.2+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "tags",
          "version": {
            "requires": "2.3.2+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "transfer",
          "version": {
            "requires": "2.3.2+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "models",
          "version": {
            "requires": "2.3.2+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "tool_actions",
          "version": {
            "requires": "2.3.2+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "client_events",
          "version": {
            "requires": "2.3.2+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "brewing",
          "version": {
            "requires": "2.3.2+1.20.1"
          }
        },
        {
          "group": "local",
          "module": "journeymap-api",
          "version": {
            "requires": "1.20-1.9-fabric-S"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.22"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.22"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "CreateOreExcavationFabric-1.20-1.5.4.jar",
          "url": "CreateOreExcavationFabric-1.20-1.5.4.jar",
          "size": 499058,
          "sha512": "8690a12261bee7db1b75fe34148fa49fdd7d18ffe9ade97ea0273b3e5a1481ad53c1b015173032d884fa93f62831d24bfb04b89e32230abfeea19383bee89490",
          "sha256": "261a4243cc599a444a34755fd120000ee9c8d5f8107e195a735a2df8437b711c",
          "sha1": "846e0b60ff6c864d2cde8957e164eb413eebdb83",
          "md5": "a22a35e8102d4853a2e8403b55defae8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "11.1.106"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "accessors",
          "version": {
            "requires": "2.3.2+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "2.3.2+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "2.3.2+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "extensions",
          "version": {
            "requires": "2.3.2+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "networking",
          "version": {
            "requires": "2.3.2+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "obj_loader",
          "version": {
            "requires": "2.3.2+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "tags",
          "version": {
            "requires": "2.3.2+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "transfer",
          "version": {
            "requires": "2.3.2+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "models",
          "version": {
            "requires": "2.3.2+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "tool_actions",
          "version": {
            "requires": "2.3.2+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "client_events",
          "version": {
            "requires": "2.3.2+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "brewing",
          "version": {
            "requires": "2.3.2+1.20.1"
          }
        },
        {
          "group": "local",
          "module": "journeymap-api",
          "version": {
            "requires": "1.20-1.9-fabric-S"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.0+1.20.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "forge-config-api-port-fabric-547434",
          "version": {
            "requires": "4583000"
          }
        },
        {
          "group": "com.tom5454.chunkstorage",
          "module": "ChunkStorageFabric-120",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.tterrag.registrate_fabric",
          "module": "Registrate",
          "version": {
            "requires": "1.3.62-MC1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc",
              "module": "*"
            },
            {
              "group": "io.github.fabricators_of_create",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-fabric-1.20.1",
          "version": {
            "requires": "0.5.1-f-build.1417+mc1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.jozufozu.flywheel",
          "module": "flywheel-fabric-1.20.1",
          "version": {
            "requires": "0.6.10-2"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.3-build.45"
          }
        },
        {
          "group": "curse.maven",
          "module": "journeymap-32274",
          "version": {
            "requires": "4841232"
          }
        },
        {
          "group": "cc.tweaked",
          "module": "cc-tweaked-1.20.1-fabric",
          "version": {
            "requires": "1.108.4"
          }
        }
      ],
      "files": [
        {
          "name": "CreateOreExcavationFabric-1.20-1.5.4.jar",
          "url": "CreateOreExcavationFabric-1.20-1.5.4.jar",
          "size": 499058,
          "sha512": "8690a12261bee7db1b75fe34148fa49fdd7d18ffe9ade97ea0273b3e5a1481ad53c1b015173032d884fa93f62831d24bfb04b89e32230abfeea19383bee89490",
          "sha256": "261a4243cc599a444a34755fd120000ee9c8d5f8107e195a735a2df8437b711c",
          "sha1": "846e0b60ff6c864d2cde8957e164eb413eebdb83",
          "md5": "a22a35e8102d4853a2e8403b55defae8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "CreateOreExcavationFabric-1.20-1.5.4-sources.jar",
          "url": "CreateOreExcavationFabric-1.20-1.5.4-sources.jar",
          "size": 296200,
          "sha512": "ef1098a4607cb754053432edf7fb136ea3367ad6c62499816db57ea6772ce049bccc38151f88411a879c954719c546f4e3a0e6d239afbc3d94fb3c0a34d16ef9",
          "sha256": "22a4779b6060dfba74125e811466459910b7c71ef7b834be52dbf1fcc4d2224c",
          "sha1": "eab371daf53d2117ca12c170211cb29c3a8d010e",
          "md5": "f088fcb66864ebba757a4a39f43e67f5"
        }
      ]
    }
  ]
}
