{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.toms_storage",
    "module": "TomsStorage-26.1",
    "version": "2.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "TomsStorage-26.1-2.9.0.jar",
          "url": "TomsStorage-26.1-2.9.0.jar",
          "size": 824861,
          "sha512": "e8b4f50452942cea908375fcf8f859124d82a4ffde98f15986485e922f9d71eecbc62688bef6a77c4546ed3bc1bc7513014991aadb2f8aa3bdb8db5f89cf4ca2",
          "sha256": "f265721166b86f1aa19219332bb4d8df05fb7c688c5c00e72962879f5951afa6",
          "sha1": "af45af6cee8c8a88141b08283acb030c98fa3903",
          "md5": "9ef1f5c3f1344fc6909ddcd52bbc874c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-neoforge",
          "version": {
            "requires": "21.11.814"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-neoforge",
          "version": {
            "requires": "18.0.145"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-neoforge",
          "version": {
            "requires": "16.1.4"
          }
        },
        {
          "group": "curse.maven",
          "module": "polymorph-388800",
          "version": {
            "requires": "5995380"
          }
        },
        {
          "group": "curse.maven",
          "module": "the-one-probe-245211",
          "version": {
            "requires": "5502323"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "7313008"
          }
        },
        {
          "group": "top.theillusivec4.curios",
          "module": "curios-neoforge",
          "version": {
            "requires": "11.0.1+1.21.5"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-neoforge",
          "version": {
            "requires": "1.1.7+1.21"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.11-neoforge",
          "version": {
            "requires": "27.3.0.14"
          }
        }
      ],
      "files": [
        {
          "name": "TomsStorage-26.1-2.9.0.jar",
          "url": "TomsStorage-26.1-2.9.0.jar",
          "size": 824861,
          "sha512": "e8b4f50452942cea908375fcf8f859124d82a4ffde98f15986485e922f9d71eecbc62688bef6a77c4546ed3bc1bc7513014991aadb2f8aa3bdb8db5f89cf4ca2",
          "sha256": "f265721166b86f1aa19219332bb4d8df05fb7c688c5c00e72962879f5951afa6",
          "sha1": "af45af6cee8c8a88141b08283acb030c98fa3903",
          "md5": "9ef1f5c3f1344fc6909ddcd52bbc874c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TomsStorage-26.1-2.9.0-sources.jar",
          "url": "TomsStorage-26.1-2.9.0-sources.jar",
          "size": 535184,
          "sha512": "6e856659f02d892d00364bf6c3082788817adc1617940f86750bfeb9d4753ed68d5543bdbc85f16618af05015bf44d48b4ae162d5a7191f07a432c1da917195b",
          "sha256": "3c0188e4bc073f447a0ee1e205f482beda9d3268df8b04aa497741f935af0787",
          "sha1": "b13c72329f9c1ca9d661e7b050849bb03e75a806",
          "md5": "9f049eaa82437e1019b0a755402dc2e5"
        }
      ]
    },
    {
      "name": "accessTransformerElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "TomsStorage-26.1-2.9.0-access-transformer.cfg",
          "url": "TomsStorage-26.1-2.9.0-access-transformer.cfg",
          "size": 580,
          "sha512": "54fdf56d9dfdaf8bf7935087c6b0b3ced9483c38f324cde64967381ae30892c408f87f00725c13329474d2d1a58ccd4dd7f2fafb1071037842aa0bf6160c75d3",
          "sha256": "654f2b47449578b9ba65586cd2c1b89f128c00ec3c035436dbc714badc6c289a",
          "sha1": "82eb657c2ab86d84fd8f198f4eb64e4df564e315",
          "md5": "1819b5c4f40faba330a37ed08e2432fd"
        }
      ]
    }
  ]
}
