{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.createoreexcavation",
    "module": "CreateOreExcavationFabric-1.20",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "11.1.106"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.22"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.22"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "CreateOreExcavationFabric-1.20-1.3.0.jar",
          "url": "CreateOreExcavationFabric-1.20-1.3.0.jar",
          "size": 336600,
          "sha512": "2d771c8fa110cc225d5ffecd335512836c0d11015feeb0f11199cc326c9fd4ed35b06540d80a229a033c4d202a4c04bfcd04eadcb255fa8c653cf34395a91b66",
          "sha256": "ec1add201705f124b0e3972c39493bc9befb6c71e7041005743287366763ab8f",
          "sha1": "e469098d053f5aca5804d76a05c9a6115140c277",
          "md5": "377159d0a5ca3dfdc53525e097019306"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "11.1.106"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.87.0+1.20.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "forge-config-api-port-fabric-547434",
          "version": {
            "requires": "4583000"
          }
        },
        {
          "group": "com.tom5454.chunkstorage",
          "module": "ChunkStorageFabric-120",
          "version": {
            "requires": "1.0.3"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.tterrag.registrate_fabric",
          "module": "Registrate",
          "version": {
            "requires": "1.3.62-MC1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc",
              "module": "*"
            },
            {
              "group": "io.github.fabricators_of_create",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-fabric-1.20.1",
          "version": {
            "requires": "0.5.1-d-build.1161+mc1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "Porting-Lib",
          "version": {
            "requires": "2.1.1127+1.20"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.jozufozu.flywheel",
          "module": "flywheel-fabric-1.20.1",
          "version": {
            "requires": "0.6.9-1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "CreateOreExcavationFabric-1.20-1.3.0.jar",
          "url": "CreateOreExcavationFabric-1.20-1.3.0.jar",
          "size": 336600,
          "sha512": "2d771c8fa110cc225d5ffecd335512836c0d11015feeb0f11199cc326c9fd4ed35b06540d80a229a033c4d202a4c04bfcd04eadcb255fa8c653cf34395a91b66",
          "sha256": "ec1add201705f124b0e3972c39493bc9befb6c71e7041005743287366763ab8f",
          "sha1": "e469098d053f5aca5804d76a05c9a6115140c277",
          "md5": "377159d0a5ca3dfdc53525e097019306"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "CreateOreExcavationFabric-1.20-1.3.0-sources.jar",
          "url": "CreateOreExcavationFabric-1.20-1.3.0-sources.jar",
          "size": 172107,
          "sha512": "15eccf9da0101001bf034f36717d344cca998a66e57f1cb6ae2df08ad111c6deaca2eb11d88eab1cb29f7d103bac15633cb1abd9c92d7a73f258af954b4ec2a6",
          "sha256": "b7b602f376659a8ce7b874c0bf31d0cf2f71f4792e02383313f82bdcc9250b1f",
          "sha1": "085f7713972574b2a2a890a9261fff071d41785f",
          "md5": "267898c2a72013b1bd5ffb6f20ebefcd"
        }
      ]
    }
  ]
}
