{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.toms_storage",
    "module": "TomsStorage-1.21.11",
    "version": "2.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "TomsStorage-1.21.11-2.8.1.jar",
          "url": "TomsStorage-1.21.11-2.8.1.jar",
          "size": 872250,
          "sha512": "ba026f0fff34ae3c44e2e669cdafe10f135cf9260892d8b59286d635f4661928efa9846c82e3613ff6c1b3a116735c1b81b58f0f5b80713491542de46d58cbe3",
          "sha256": "cf5f0cc22e1bc26aea4bb15e8b0405c18422efdaade83a99212553ed8fa6374d",
          "sha1": "575115d7c5d7ffbe70d78ac82d86ccc5d69c0fd6",
          "md5": "7385c7d12dedbbae4459b58b4b81b8d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "7313008"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-neoforge",
          "version": {
            "requires": "21.11.816"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-neoforge",
          "version": {
            "requires": "18.0.145"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-neoforge",
          "version": {
            "requires": "16.1.4"
          }
        },
        {
          "group": "curse.maven",
          "module": "polymorph-388800",
          "version": {
            "requires": "5995380"
          }
        },
        {
          "group": "curse.maven",
          "module": "the-one-probe-245211",
          "version": {
            "requires": "5502323"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.11-neoforge",
          "version": {
            "requires": "27.3.0.14"
          }
        },
        {
          "group": "top.theillusivec4.curios",
          "module": "curios-neoforge",
          "version": {
            "requires": "11.0.1+1.21.5"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-neoforge",
          "version": {
            "requires": "1.1.7+1.21"
          }
        }
      ],
      "files": [
        {
          "name": "TomsStorage-1.21.11-2.8.1.jar",
          "url": "TomsStorage-1.21.11-2.8.1.jar",
          "size": 872250,
          "sha512": "ba026f0fff34ae3c44e2e669cdafe10f135cf9260892d8b59286d635f4661928efa9846c82e3613ff6c1b3a116735c1b81b58f0f5b80713491542de46d58cbe3",
          "sha256": "cf5f0cc22e1bc26aea4bb15e8b0405c18422efdaade83a99212553ed8fa6374d",
          "sha1": "575115d7c5d7ffbe70d78ac82d86ccc5d69c0fd6",
          "md5": "7385c7d12dedbbae4459b58b4b81b8d1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TomsStorage-1.21.11-2.8.1-sources.jar",
          "url": "TomsStorage-1.21.11-2.8.1-sources.jar",
          "size": 551413,
          "sha512": "4c2320aeac3b04624fef3c2e3db99e6a2b82b1891ac02911e3dc07fb298fd168cd35f825775a39761f5ab9afceb82839eef1ee2cc94a59fe4dfb5d54e4988d80",
          "sha256": "5ef34e78dd94bb24187817b9d434de510dd0536643ef5ad4d88fcd7e6671b113",
          "sha1": "8f5d8886d59ff9841bd7272c1560d8003e4a7781",
          "md5": "153b2107778a84f661e7f7b395816e71"
        }
      ]
    }
  ]
}
