{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.aerocables",
    "module": "AeroCables",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "AeroCables-0.4.0.jar",
          "url": "AeroCables-0.4.0.jar",
          "size": 203873,
          "sha512": "3c4fc5ef77ca99c34b97a9249b4e5def572d9d9314c75b9a4105950486900582c2f2e1919f829e13de6231b5a8f2d885f6425de61aa93c892c9212addb2c2310",
          "sha256": "33bddfe2eb12473922e008393f8ee24e49d8d004012f85d90d2d28393724fb17",
          "sha1": "f38a48ff5ef72a79f1d56582f9cda47b88fe9268",
          "md5": "3ca7348a5d5b9037fd423a78b2d3d3d3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.10-280"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.21.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "ponder-neoforge",
          "version": {
            "requires": "1.0.82+mc1.21.1"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+67"
          }
        },
        {
          "group": "com.tom5454.cpm",
          "module": "CustomPlayerModels-1.21",
          "version": {
            "requires": "0.6.25a"
          }
        },
        {
          "group": "com.tom5454.toms_storage",
          "module": "TomsStorage-121",
          "version": {
            "requires": "2.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6011258"
          }
        },
        {
          "group": "dev.ryanhcode.sable",
          "module": "sable-neoforge-1.21.1",
          "version": {
            "requires": "[1.2.1,)"
          }
        },
        {
          "group": "dev.eriksonn.aeronautics",
          "module": "aeronautics-neoforge-1.21.1",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "dev.simulated_team.simulated",
          "module": "simulated-neoforge-1.21.1",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "integrated-dynamics-236307",
          "version": {
            "requires": "7648811"
          }
        },
        {
          "group": "curse.maven",
          "module": "cyclops-core-232758",
          "version": {
            "requires": "7637998"
          }
        },
        {
          "group": "curse.maven",
          "module": "common-capabilities-247007",
          "version": {
            "requires": "7361876"
          }
        },
        {
          "group": "curse.maven",
          "module": "refined-storage-243076",
          "version": {
            "requires": "7610477"
          }
        },
        {
          "group": "curse.maven",
          "module": "applied-energistics-2-223794",
          "version": {
            "requires": "7027323"
          }
        },
        {
          "group": "curse.maven",
          "module": "guideme-1173950",
          "version": {
            "requires": "7127444"
          }
        },
        {
          "group": "cc.tweaked",
          "module": "cc-tweaked-1.21.1-forge",
          "version": {
            "requires": "1.115.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "mekanism-268560",
          "version": {
            "requires": "7904058"
          }
        },
        {
          "group": "com.tom5454.peripherals",
          "module": "TomsPeripherals-121",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.21.2.313"
          }
        },
        {
          "group": "dev.ryanhcode.offroad",
          "module": "offroad-neoforge-1.21.1",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "AeroCables-0.4.0.jar",
          "url": "AeroCables-0.4.0.jar",
          "size": 203873,
          "sha512": "3c4fc5ef77ca99c34b97a9249b4e5def572d9d9314c75b9a4105950486900582c2f2e1919f829e13de6231b5a8f2d885f6425de61aa93c892c9212addb2c2310",
          "sha256": "33bddfe2eb12473922e008393f8ee24e49d8d004012f85d90d2d28393724fb17",
          "sha1": "f38a48ff5ef72a79f1d56582f9cda47b88fe9268",
          "md5": "3ca7348a5d5b9037fd423a78b2d3d3d3"
        }
      ]
    }
  ]
}
