{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.toms_trading",
    "module": "TomsTradingNetworkFabric-1206",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.6-common-api",
          "version": {
            "requires": "18.0.0.59"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.6-fabric-api",
          "version": {
            "requires": "18.0.0.59"
          }
        }
      ],
      "files": [
        {
          "name": "TomsTradingNetworkFabric-1206-0.3.0.jar",
          "url": "TomsTradingNetworkFabric-1206-0.3.0.jar",
          "size": 228517,
          "sha512": "f3ee7f28040099fdd06c6872e406873b0dc8ebc5adf371babc2fedb29a28c409e56dd2b8ccdf28aea07bbd3769265a9d98bcb4c856444097d219959a71e36346",
          "sha256": "a5b6a4d82ab2a47404ce663d2ac371e00b6305b62aff27e559932b1f958502c4",
          "sha1": "759f35ca7c66de3ad19d36c958e2c8d501f11afb",
          "md5": "5f3e65f753916a177cc7de0bd610cdeb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.97.8+1.20.6"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "10.0.0-beta.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "12.0.28"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5366607"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "15.0.728"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "dev.architectury",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.6-fabric",
          "version": {
            "requires": "18.0.0.59"
          }
        }
      ],
      "files": [
        {
          "name": "TomsTradingNetworkFabric-1206-0.3.0.jar",
          "url": "TomsTradingNetworkFabric-1206-0.3.0.jar",
          "size": 228517,
          "sha512": "f3ee7f28040099fdd06c6872e406873b0dc8ebc5adf371babc2fedb29a28c409e56dd2b8ccdf28aea07bbd3769265a9d98bcb4c856444097d219959a71e36346",
          "sha256": "a5b6a4d82ab2a47404ce663d2ac371e00b6305b62aff27e559932b1f958502c4",
          "sha1": "759f35ca7c66de3ad19d36c958e2c8d501f11afb",
          "md5": "5f3e65f753916a177cc7de0bd610cdeb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TomsTradingNetworkFabric-1206-0.3.0-sources.jar",
          "url": "TomsTradingNetworkFabric-1206-0.3.0-sources.jar",
          "size": 169539,
          "sha512": "1d5b75dcf638886459eaf046cb45983741e75b1c091f9f6bd1fb45ee290f12f1c8d0a7c00b836cb5894927ed5f5a9eb0691623544c2c187f509608d8bb13e7cb",
          "sha256": "45b22ff76af4e4e49e012f749e770e3370eb01a3ece9530eb1e470a91aacd46d",
          "sha1": "03aef3d856d30fd6db0eefd38dd6ff06ddbaf8f9",
          "md5": "2e54144bfe1fac98bb2e6003808fb625"
        }
      ]
    }
  ]
}
