{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.toms_storage",
    "module": "TomsStorage-1206",
    "version": "1.6.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "TomsStorage-1206-1.6.14.jar",
          "url": "TomsStorage-1206-1.6.14.jar",
          "size": 506441,
          "sha512": "50663b67ed3afbb6c6c682a1e29785cec9ffbc843ace0b2b670c54386eb01f91a0768504f28a18a1f69dcd573fd0fef8b71276c3231846c06d32b018d09fa53b",
          "sha256": "2a7c8338451138199d1acf8c39f814d7a9baccc57caaf9a64175f80db6d1663b",
          "sha1": "43ec0eda76b9563f9ec89a3e568a5fc7c70bf17f",
          "md5": "69e5e812eb5d14f15643e9db83b12edb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-neoforge",
          "version": {
            "requires": "15.0.728"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-neoforge",
          "version": {
            "requires": "14.0.126"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-neoforge",
          "version": {
            "requires": "12.0.27"
          }
        },
        {
          "group": "top.theillusivec4.curios",
          "module": "curios-neoforge",
          "version": {
            "requires": "8.0.0-beta+1.20.6"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-neoforge",
          "version": {
            "requires": "1.1.6+1.20.6"
          }
        }
      ],
      "files": [
        {
          "name": "TomsStorage-1206-1.6.14.jar",
          "url": "TomsStorage-1206-1.6.14.jar",
          "size": 506441,
          "sha512": "50663b67ed3afbb6c6c682a1e29785cec9ffbc843ace0b2b670c54386eb01f91a0768504f28a18a1f69dcd573fd0fef8b71276c3231846c06d32b018d09fa53b",
          "sha256": "2a7c8338451138199d1acf8c39f814d7a9baccc57caaf9a64175f80db6d1663b",
          "sha1": "43ec0eda76b9563f9ec89a3e568a5fc7c70bf17f",
          "md5": "69e5e812eb5d14f15643e9db83b12edb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TomsStorage-1206-1.6.14-sources.jar",
          "url": "TomsStorage-1206-1.6.14-sources.jar",
          "size": 299205,
          "sha512": "af35153c17ce0aa6b8dad0f52fa82822300a106f40482c744423d93bd9a5899fbbd9111d6bbf03dcc71c1f5c48d845745f4b043a03f20895823de229c0f34ec6",
          "sha256": "583530b98cca0cfd5c380266880d09a00a66a22aae0ec379bacc056f625a0695",
          "sha1": "db4f3a8dd09e0a9d0798bcbe6b6df4f490cdd161",
          "md5": "432ff04d7b7c8c5b991a2204e5712f58"
        }
      ]
    }
  ]
}
