{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.createcontraptionterminals",
    "module": "CreateContraptionTerminalsFabric-1.20",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "11.1.106"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.22"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.22"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "CreateContraptionTerminalsFabric-1.20-1.1.0.jar",
          "url": "CreateContraptionTerminalsFabric-1.20-1.1.0.jar",
          "size": 87992,
          "sha512": "10d9b00a2165c12b5d552e1dfcdb744a3ee74434dadd9bf698aee1e8545856110cf89b859e56d89b270a56a21afe9394279bb018ccde492cd6f78628c3b05605",
          "sha256": "6ad3fddaa8d732a5d1213991ef5b3a334b5f88824b24c3819158bea407cee921",
          "sha1": "5552793e45de911ef00542f6e8f6fc4263098524",
          "md5": "ec13b6bc46101d527afbe37777e777f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "11.1.106"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.0+1.20.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "forge-config-api-port-fabric-547434",
          "version": {
            "requires": "4583000"
          }
        },
        {
          "group": "com.tterrag.registrate_fabric",
          "module": "Registrate",
          "version": {
            "requires": "1.3.62-MC1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc",
              "module": "*"
            },
            {
              "group": "io.github.fabricators_of_create",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.simibubi.create",
          "module": "create-fabric-1.20.1",
          "version": {
            "requires": "0.5.1-j-build.1631+mc1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric",
              "module": "*"
            }
          ]
        },
        {
          "group": "local",
          "module": "toms_storage_fabric-1.20",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "dev.architectury",
              "module": "*"
            },
            {
              "group": "net.fabricmc.fabric",
              "module": "*"
            },
            {
              "group": "me.shedaniel",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.22"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "CreateContraptionTerminalsFabric-1.20-1.1.0.jar",
          "url": "CreateContraptionTerminalsFabric-1.20-1.1.0.jar",
          "size": 87992,
          "sha512": "10d9b00a2165c12b5d552e1dfcdb744a3ee74434dadd9bf698aee1e8545856110cf89b859e56d89b270a56a21afe9394279bb018ccde492cd6f78628c3b05605",
          "sha256": "6ad3fddaa8d732a5d1213991ef5b3a334b5f88824b24c3819158bea407cee921",
          "sha1": "5552793e45de911ef00542f6e8f6fc4263098524",
          "md5": "ec13b6bc46101d527afbe37777e777f1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "CreateContraptionTerminalsFabric-1.20-1.1.0-sources.jar",
          "url": "CreateContraptionTerminalsFabric-1.20-1.1.0-sources.jar",
          "size": 79756,
          "sha512": "4049057aa0c6c305549e477bc5bc27227cdf88784d5df34470b98fb7303c3c6cd5f2e1996fd91b52634d5559e2760daf804b165827f5f9d9cd5b7556354d4265",
          "sha256": "d60e6405479d176f9f6ddd285b9a51094bb4ac58863529f506810cc218bb5c97",
          "sha1": "7fdc9ca65509e1f3ce9ddecd6b52a49d87e3dba7",
          "md5": "9503b45a606f030fd78a8c752c403fe3"
        }
      ]
    }
  ]
}
