{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.createstockbridge",
    "module": "CreateStockBridge-1.21",
    "version": "0.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "CreateStockBridge-1.21-0.1.5.jar",
          "url": "CreateStockBridge-1.21-0.1.5.jar",
          "size": 171779,
          "sha512": "de17f64f493d3f12b80832f365e7d01c2fc05e1d72bd4dd25253a952fe7e75f169c636b8871a8350f00387ec53c61c341f8a96f8134d8cce88f456f3a7dc0157",
          "sha256": "3da896d7617f0f9d79d97bef99e0f915b1a40cd9c14b2ba14471a2420736ec68",
          "sha1": "517f2c377f6733adf87b026d3c69fa41316e6a90",
          "md5": "98a2e3020feaea35c02b2fe705052c4a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "the-one-probe-245211",
          "version": {
            "requires": "5502323"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5529595"
          }
        },
        {
          "group": "curse.maven",
          "module": "refined-storage-243076",
          "version": {
            "requires": "6358597"
          }
        },
        {
          "group": "curse.maven",
          "module": "applied-energistics-2-223794",
          "version": {
            "requires": "6225422"
          }
        },
        {
          "group": "curse.maven",
          "module": "guideme-1173950",
          "version": {
            "requires": "6331224"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.6-98"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.21.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.56"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.21.0.247"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "CreateStockBridge-1.21-0.1.5.jar",
          "url": "CreateStockBridge-1.21-0.1.5.jar",
          "size": 171779,
          "sha512": "de17f64f493d3f12b80832f365e7d01c2fc05e1d72bd4dd25253a952fe7e75f169c636b8871a8350f00387ec53c61c341f8a96f8134d8cce88f456f3a7dc0157",
          "sha256": "3da896d7617f0f9d79d97bef99e0f915b1a40cd9c14b2ba14471a2420736ec68",
          "sha1": "517f2c377f6733adf87b026d3c69fa41316e6a90",
          "md5": "98a2e3020feaea35c02b2fe705052c4a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "CreateStockBridge-1.21-0.1.5-sources.jar",
          "url": "CreateStockBridge-1.21-0.1.5-sources.jar",
          "size": 124431,
          "sha512": "372801cdb101a6f3ad734ebe4b589a8bad4c53e966a661ee4835545894126820ff0abfaf64f8a77c8cd2fd14a1edba49c248988da66f83363fa5e4599f6d5fcd",
          "sha256": "eaab63cdeeb57b534d0043cd04c8079d5e9161bfa61ca6437f6e05ae293348e1",
          "sha1": "aac63d220d4b6c32979e3cef6c1fb297ed2e66d6",
          "md5": "faf9588ab4fc3d9cc75558248cbf03b0"
        }
      ]
    }
  ]
}
