{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.toms_storage",
    "module": "TomsStorage-1.21.10",
    "version": "2.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "TomsStorage-1.21.10-2.6.2.jar",
          "url": "TomsStorage-1.21.10-2.6.2.jar",
          "size": 854485,
          "sha512": "f59a2b8f83bb86bf19e0c8a89cf931ac349125b36f4469420f034d38df8e235b23424c8138063d3a0c779f2dad49c5eeb91843966e24ce6d5f1e001be1f7e3cd",
          "sha256": "acb81a81c95ea495b0752cb26d0d7ff2c476957df3fa1b0ea0fa0b06ad4481fc",
          "sha1": "1ad96d7729bc879172091e2bc19709d5e707e338",
          "md5": "894d8e4706bf23fe11edb12188b5be28"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "7056468"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-neoforge",
          "version": {
            "requires": "19.0.806"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-neoforge",
          "version": {
            "requires": "18.0.145"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-neoforge",
          "version": {
            "requires": "16.1.4"
          }
        },
        {
          "group": "curse.maven",
          "module": "polymorph-388800",
          "version": {
            "requires": "5995380"
          }
        },
        {
          "group": "curse.maven",
          "module": "the-one-probe-245211",
          "version": {
            "requires": "5502323"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.10-neoforge",
          "version": {
            "requires": "26.0.0.1"
          }
        },
        {
          "group": "top.theillusivec4.curios",
          "module": "curios-neoforge",
          "version": {
            "requires": "11.0.1+1.21.5"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-neoforge",
          "version": {
            "requires": "1.1.7+1.21"
          }
        }
      ],
      "files": [
        {
          "name": "TomsStorage-1.21.10-2.6.2.jar",
          "url": "TomsStorage-1.21.10-2.6.2.jar",
          "size": 854485,
          "sha512": "f59a2b8f83bb86bf19e0c8a89cf931ac349125b36f4469420f034d38df8e235b23424c8138063d3a0c779f2dad49c5eeb91843966e24ce6d5f1e001be1f7e3cd",
          "sha256": "acb81a81c95ea495b0752cb26d0d7ff2c476957df3fa1b0ea0fa0b06ad4481fc",
          "sha1": "1ad96d7729bc879172091e2bc19709d5e707e338",
          "md5": "894d8e4706bf23fe11edb12188b5be28"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TomsStorage-1.21.10-2.6.2-sources.jar",
          "url": "TomsStorage-1.21.10-2.6.2-sources.jar",
          "size": 544695,
          "sha512": "b87f9fab306103633a3842c886caeb1451eb33f1cddc9d18cc858ee4b922ecc22094a7e7eafdcb1df4657713a93d83d7bb0d45686fef42b9bf54e2f1ddd47feb",
          "sha256": "79bda8b32d43f204dc579423bbd5c8beef9dae611b6bec8cfe778330ef092271",
          "sha1": "1553cd0581ebac3ed173f2d6f60805a107f5d39f",
          "md5": "f87f2d675b1560a74cb3d902f6fe73f3"
        }
      ]
    }
  ]
}
