{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.toms_storage",
    "module": "TomsStorage-26.1",
    "version": "2.9.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "TomsStorage-26.1-2.9.5.jar",
          "url": "TomsStorage-26.1-2.9.5.jar",
          "size": 852708,
          "sha512": "0641d2139ad2517dec9b0dee6fbd59abd2c55578a29408bd23acc3ec8ce5e17b5eeb60ad99c630b3ada8b2f56250f5201c2732ffa8f7f43b84e62cf9c5566881",
          "sha256": "01decff7432d866d0a54d26b5f78b50fbec976a7734ad1bdb66a7b41df23ad5c",
          "sha1": "41bc234a64974b7e6c932aeff584c0c302289fa4",
          "md5": "09baca57303af1193b9467e74c57c169"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "7817285"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-neoforge",
          "version": {
            "requires": "21.11.814"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-neoforge",
          "version": {
            "requires": "18.0.145"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-neoforge",
          "version": {
            "requires": "16.1.4"
          }
        },
        {
          "group": "curse.maven",
          "module": "polymorph-388800",
          "version": {
            "requires": "5995380"
          }
        },
        {
          "group": "curse.maven",
          "module": "the-one-probe-245211",
          "version": {
            "requires": "5502323"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-26.1.1-neoforge",
          "version": {
            "requires": "29.4.0.23"
          }
        },
        {
          "group": "top.theillusivec4.curios",
          "module": "curios-neoforge",
          "version": {
            "requires": "11.0.1+1.21.5"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-neoforge",
          "version": {
            "requires": "1.1.7+1.21"
          }
        }
      ],
      "files": [
        {
          "name": "TomsStorage-26.1-2.9.5.jar",
          "url": "TomsStorage-26.1-2.9.5.jar",
          "size": 852708,
          "sha512": "0641d2139ad2517dec9b0dee6fbd59abd2c55578a29408bd23acc3ec8ce5e17b5eeb60ad99c630b3ada8b2f56250f5201c2732ffa8f7f43b84e62cf9c5566881",
          "sha256": "01decff7432d866d0a54d26b5f78b50fbec976a7734ad1bdb66a7b41df23ad5c",
          "sha1": "41bc234a64974b7e6c932aeff584c0c302289fa4",
          "md5": "09baca57303af1193b9467e74c57c169"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TomsStorage-26.1-2.9.5-sources.jar",
          "url": "TomsStorage-26.1-2.9.5-sources.jar",
          "size": 545602,
          "sha512": "db0796561797e7c9f3b236b025c2e94a06689497dfc9b51a5386251045484b94c48ca1c881f20ff62515e75e35eb8edf6480a5add38812c219664ad84b199986",
          "sha256": "44a4e13f3d6cf41b9cb3f6a3cc12971c3969e0dfe49d884fd30089aabcec8a2b",
          "sha1": "c105b3854309df8c477c24599d487db5c4f8e465",
          "md5": "78f9b57651ecd0d0bce71e184ba44632"
        }
      ]
    },
    {
      "name": "accessTransformerElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "TomsStorage-26.1-2.9.5-access-transformer.cfg",
          "url": "TomsStorage-26.1-2.9.5-access-transformer.cfg",
          "size": 580,
          "sha512": "54fdf56d9dfdaf8bf7935087c6b0b3ced9483c38f324cde64967381ae30892c408f87f00725c13329474d2d1a58ccd4dd7f2fafb1071037842aa0bf6160c75d3",
          "sha256": "654f2b47449578b9ba65586cd2c1b89f128c00ec3c035436dbc714badc6c289a",
          "sha1": "82eb657c2ab86d84fd8f198f4eb64e4df564e315",
          "md5": "1819b5c4f40faba330a37ed08e2432fd"
        }
      ]
    }
  ]
}
