{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.toms_trading",
    "module": "TomsTradingNetworkFabric-121",
    "version": "0.2.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "TomsTradingNetworkFabric-121-0.2.13.jar",
          "url": "TomsTradingNetworkFabric-121-0.2.13.jar",
          "size": 206910,
          "sha512": "012ac87348f86aafdaec30d498a2a419085a32215bccca6a2e9197bbfea1fb865db91578a4c6e90d0c8eb7d35cf34e6705a40a702a77b06d053823b7b45870af",
          "sha256": "6b0a6f8abc485dcb17b971283917ee9b73a7a8cd2c40eff449503b8abdf38a0e",
          "sha1": "9f5be7b0794493080caff34d174f552a67f694f7",
          "md5": "1b5c9df8fec2b882c4de144300633156"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.99.1+1.21"
          }
        }
      ],
      "files": [
        {
          "name": "TomsTradingNetworkFabric-121-0.2.13.jar",
          "url": "TomsTradingNetworkFabric-121-0.2.13.jar",
          "size": 206910,
          "sha512": "012ac87348f86aafdaec30d498a2a419085a32215bccca6a2e9197bbfea1fb865db91578a4c6e90d0c8eb7d35cf34e6705a40a702a77b06d053823b7b45870af",
          "sha256": "6b0a6f8abc485dcb17b971283917ee9b73a7a8cd2c40eff449503b8abdf38a0e",
          "sha1": "9f5be7b0794493080caff34d174f552a67f694f7",
          "md5": "1b5c9df8fec2b882c4de144300633156"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TomsTradingNetworkFabric-121-0.2.13-sources.jar",
          "url": "TomsTradingNetworkFabric-121-0.2.13-sources.jar",
          "size": 160171,
          "sha512": "dca1df0f76305c69cf8cef0a267a03b2caed33289544b8b646cad20904b9cef784f3ade5880aebd0d2b863f41aa657b6b376c2fe4da5fc02ceba2d6f6c04793e",
          "sha256": "14ab7051ac16a8c7d78fd4e53e326464cedf522425596969d22eb23a13103aff",
          "sha1": "6c67c0a346b546a96775e5a171fdea47c46c43aa",
          "md5": "aded48694caaba0e3d04eca4b0ffe998"
        }
      ]
    }
  ]
}
