{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.toms_storage",
    "module": "TomsStorage-26.1",
    "version": "2.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "TomsStorage-26.1-2.10.0.jar",
          "url": "TomsStorage-26.1-2.10.0.jar",
          "size": 859949,
          "sha512": "0f471600f7e38fc51f7b2dabbd060e6b97a86813ffff8e8f5e99c4cd32e9dac49ef808eaea8a3eef28da8077d8aaf15f0479f16b9a9ae545e134d3fe579dc614",
          "sha256": "d05da8a81197e5cefd702d83bf8c7e1ed5d65e3d3a01d7b6fb3dd747c5176522",
          "sha1": "92996758e62d0861cf9dbceb970e9b1464a196e4",
          "md5": "1a8c10bf60941058a247a354d2875269"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "7817285"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-neoforge",
          "version": {
            "requires": "21.11.814"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-neoforge",
          "version": {
            "requires": "18.0.145"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-neoforge",
          "version": {
            "requires": "16.1.4"
          }
        },
        {
          "group": "curse.maven",
          "module": "polymorph-388800",
          "version": {
            "requires": "5995380"
          }
        },
        {
          "group": "curse.maven",
          "module": "the-one-probe-245211",
          "version": {
            "requires": "5502323"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-26.1.2-neoforge",
          "version": {
            "requires": "29.16.0.48"
          }
        },
        {
          "group": "top.theillusivec4.curios",
          "module": "curios-neoforge",
          "version": {
            "requires": "11.0.1+1.21.5"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-neoforge",
          "version": {
            "requires": "1.1.7+1.21"
          }
        }
      ],
      "files": [
        {
          "name": "TomsStorage-26.1-2.10.0.jar",
          "url": "TomsStorage-26.1-2.10.0.jar",
          "size": 859949,
          "sha512": "0f471600f7e38fc51f7b2dabbd060e6b97a86813ffff8e8f5e99c4cd32e9dac49ef808eaea8a3eef28da8077d8aaf15f0479f16b9a9ae545e134d3fe579dc614",
          "sha256": "d05da8a81197e5cefd702d83bf8c7e1ed5d65e3d3a01d7b6fb3dd747c5176522",
          "sha1": "92996758e62d0861cf9dbceb970e9b1464a196e4",
          "md5": "1a8c10bf60941058a247a354d2875269"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TomsStorage-26.1-2.10.0-sources.jar",
          "url": "TomsStorage-26.1-2.10.0-sources.jar",
          "size": 552961,
          "sha512": "e991d79737a008ba8078ea965fa0ae62937b74cb45445da93c23155fb2084ac1d14bc06b9f40d801d24db2499e27895e7b20c16ac7885057c786685441caa2d5",
          "sha256": "62b58ecadba09be0d7a7cbf398b1c1be9e9c7d79b8521c59f350b41983a22713",
          "sha1": "54d07ab40dcb29ebd46f70838efb54f0c4c97b25",
          "md5": "3ff22d6c1cc2751f80b79f4a70789a48"
        }
      ]
    },
    {
      "name": "accessTransformerElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "TomsStorage-26.1-2.10.0-access-transformer.cfg",
          "url": "TomsStorage-26.1-2.10.0-access-transformer.cfg",
          "size": 580,
          "sha512": "54fdf56d9dfdaf8bf7935087c6b0b3ced9483c38f324cde64967381ae30892c408f87f00725c13329474d2d1a58ccd4dd7f2fafb1071037842aa0bf6160c75d3",
          "sha256": "654f2b47449578b9ba65586cd2c1b89f128c00ec3c035436dbc714badc6c289a",
          "sha1": "82eb657c2ab86d84fd8f198f4eb64e4df564e315",
          "md5": "1819b5c4f40faba330a37ed08e2432fd"
        }
      ]
    }
  ]
}
