{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.createoreexcavation",
    "module": "CreateOreExcavationFabric-1.20",
    "version": "1.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "11.1.106"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "accessors",
          "version": {
            "requires": "2.3.12+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "2.3.12+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "2.3.12+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "extensions",
          "version": {
            "requires": "2.3.12+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "networking",
          "version": {
            "requires": "2.3.12+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "obj_loader",
          "version": {
            "requires": "2.3.12+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "tags",
          "version": {
            "requires": "2.3.12+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "transfer",
          "version": {
            "requires": "2.3.12+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "models",
          "version": {
            "requires": "2.3.12+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "tool_actions",
          "version": {
            "requires": "2.3.12+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "client_events",
          "version": {
            "requires": "2.3.12+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "brewing",
          "version": {
            "requires": "2.3.12+1.20.1"
          }
        },
        {
          "group": "local",
          "module": "journeymap-api",
          "version": {
            "requires": "1.20-1.9-fabric-S"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.20.0.116"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.116"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "CreateOreExcavationFabric-1.20-1.6.0.jar",
          "url": "CreateOreExcavationFabric-1.20-1.6.0.jar",
          "size": 506164,
          "sha512": "4f31e07104ed52af4dd6372f71ce46dda8ee870a56ca018cc1c857674c179345576470fb29631498eeef3f03a3d4cf099c5a3253ee070c848b5f666dbbea67ea",
          "sha256": "ed297b6486b23cd3d3a2687f1252cc65c5056e8842b73dff9e0b2750a36c01a2",
          "sha1": "e93b036bca32026c220210ae11d1b565c8de1edf",
          "md5": "f6bdeb508d7a8473adaa1cabae772f87"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "11.1.106"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "accessors",
          "version": {
            "requires": "2.3.12+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "base",
          "version": {
            "requires": "2.3.12+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "entity",
          "version": {
            "requires": "2.3.12+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "extensions",
          "version": {
            "requires": "2.3.12+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "networking",
          "version": {
            "requires": "2.3.12+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "obj_loader",
          "version": {
            "requires": "2.3.12+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "tags",
          "version": {
            "requires": "2.3.12+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "transfer",
          "version": {
            "requires": "2.3.12+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "models",
          "version": {
            "requires": "2.3.12+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "tool_actions",
          "version": {
            "requires": "2.3.12+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "client_events",
          "version": {
            "requires": "2.3.12+1.20.1"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "brewing",
          "version": {
            "requires": "2.3.12+1.20.1"
          }
        },
        {
          "group": "local",
          "module": "journeymap-api",
          "version": {
            "requires": "1.20-1.9-fabric-S"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.6+1.20.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "forge-config-api-port-fabric-547434",
          "version": {
            "requires": "4583000"
          }
        },
        {
          "group": "com.tom5454.chunkstorage",
          "module": "ChunkStorageFabric-120",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-loader",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.tterrag.registrate_fabric",
          "module": "Registrate",
          "version": {
            "requires": "1.3.62-MC1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc",
              "module": "*"
            },
            {
              "group": "io.github.fabricators_of_create",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "9.1.12"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-fabric-1.20.1",
          "version": {
            "requires": "6.0.7.0+mc1.20.1-build.1716"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-fabric-1.20.1",
          "version": {
            "requires": "1.0.5-264"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-Fabric-1.20.1",
          "version": {
            "requires": "1.0.91"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.3-build.45"
          }
        },
        {
          "group": "curse.maven",
          "module": "journeymap-32274",
          "version": {
            "requires": "4841232"
          }
        },
        {
          "group": "cc.tweaked",
          "module": "cc-tweaked-1.20.1-fabric",
          "version": {
            "requires": "1.108.4"
          }
        }
      ],
      "files": [
        {
          "name": "CreateOreExcavationFabric-1.20-1.6.0.jar",
          "url": "CreateOreExcavationFabric-1.20-1.6.0.jar",
          "size": 506164,
          "sha512": "4f31e07104ed52af4dd6372f71ce46dda8ee870a56ca018cc1c857674c179345576470fb29631498eeef3f03a3d4cf099c5a3253ee070c848b5f666dbbea67ea",
          "sha256": "ed297b6486b23cd3d3a2687f1252cc65c5056e8842b73dff9e0b2750a36c01a2",
          "sha1": "e93b036bca32026c220210ae11d1b565c8de1edf",
          "md5": "f6bdeb508d7a8473adaa1cabae772f87"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "CreateOreExcavationFabric-1.20-1.6.0-sources.jar",
          "url": "CreateOreExcavationFabric-1.20-1.6.0-sources.jar",
          "size": 301702,
          "sha512": "53511ca001ed993a1be33804da172a2927c4bf851eab59470287364be5380e74e1b4d5a4c00fd9d11986992790db3fa0a82946e1ee29e37a26b05c1524f77be4",
          "sha256": "a7f44d9b322b50deb04bd596435df449ca4d49864455400af97005735f01ed1b",
          "sha1": "b77708cce016e11f345c23818b0df58a751cd71c",
          "md5": "41552f61c356cf2b5f5c42263da93a74"
        }
      ]
    }
  ]
}
