{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.aerocables",
    "module": "AeroCables",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "AeroCables-0.3.0.jar",
          "url": "AeroCables-0.3.0.jar",
          "size": 191947,
          "sha512": "4c47404b5e2bf17a0f44b52f2b00a836281a51bbb91d03968af3c0a2f018150f1eef4490d7cdf86069c9f5a5b175ee8af25e10c0f2d3455a24541dd8a070afc5",
          "sha256": "fc2b8a8c793e84f968b86b0136c55cd7e7429958cc153fef2a467269e8243bc6",
          "sha1": "6d780ebd9bfff5902d8f237c6ac08d4d8904163f",
          "md5": "ce308a0d6278a86ce937e5a68624d9f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.10-280"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.21.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "ponder-neoforge",
          "version": {
            "requires": "1.0.82+mc1.21.1"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+67"
          }
        },
        {
          "group": "com.tom5454.cpm",
          "module": "CustomPlayerModels-1.21",
          "version": {
            "requires": "0.6.25a"
          }
        },
        {
          "group": "com.tom5454.toms_storage",
          "module": "TomsStorage-121",
          "version": {
            "requires": "2.3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "6011258"
          }
        },
        {
          "group": "dev.ryanhcode.sable",
          "module": "sable-neoforge-1.21.1",
          "version": {
            "requires": "[1.2.1,)"
          }
        },
        {
          "group": "dev.eriksonn.aeronautics",
          "module": "aeronautics-neoforge-1.21.1",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "dev.simulated_team.simulated",
          "module": "simulated-neoforge-1.21.1",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "integrated-dynamics-236307",
          "version": {
            "requires": "7648811"
          }
        },
        {
          "group": "curse.maven",
          "module": "cyclops-core-232758",
          "version": {
            "requires": "7637998"
          }
        },
        {
          "group": "curse.maven",
          "module": "common-capabilities-247007",
          "version": {
            "requires": "7361876"
          }
        },
        {
          "group": "curse.maven",
          "module": "refined-storage-243076",
          "version": {
            "requires": "7610477"
          }
        },
        {
          "group": "curse.maven",
          "module": "applied-energistics-2-223794",
          "version": {
            "requires": "7027323"
          }
        },
        {
          "group": "curse.maven",
          "module": "guideme-1173950",
          "version": {
            "requires": "7127444"
          }
        },
        {
          "group": "curse.maven",
          "module": "mekanism-268560",
          "version": {
            "requires": "7904058"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.21.2.313"
          }
        },
        {
          "group": "dev.ryanhcode.offroad",
          "module": "offroad-neoforge-1.21.1",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "AeroCables-0.3.0.jar",
          "url": "AeroCables-0.3.0.jar",
          "size": 191947,
          "sha512": "4c47404b5e2bf17a0f44b52f2b00a836281a51bbb91d03968af3c0a2f018150f1eef4490d7cdf86069c9f5a5b175ee8af25e10c0f2d3455a24541dd8a070afc5",
          "sha256": "fc2b8a8c793e84f968b86b0136c55cd7e7429958cc153fef2a467269e8243bc6",
          "sha1": "6d780ebd9bfff5902d8f237c6ac08d4d8904163f",
          "md5": "ce308a0d6278a86ce937e5a68624d9f2"
        }
      ]
    }
  ]
}
