{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.toms_trading",
    "module": "TomsTradingNetwork-121",
    "version": "0.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "TomsTradingNetwork-121-0.3.3.jar",
          "url": "TomsTradingNetwork-121-0.3.3.jar",
          "size": 269077,
          "sha512": "ef230cc0f1dd2365fa6908d4fb0461591b201feda785a09369650aec15c2b81d222097244379651a18fe59ce46f96df351725c2f26c9f5932e1f51782d331f20",
          "sha256": "1bfce1ac9036cd45668c473afee63f7548b64b31430125783c7b16dca5cb7cce",
          "sha1": "bd83a79cbfe52a7d969430fc3ac2cfdaf9115640",
          "md5": "d48f08297f6340cc055c5c8272cb01b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-neoforge",
          "version": {
            "requires": "16.0.729"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-neoforge",
          "version": {
            "requires": "15.0.127"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-neoforge",
          "version": {
            "requires": "13.0.4"
          }
        },
        {
          "group": "curse.maven",
          "module": "the-one-probe-245211",
          "version": {
            "requires": "6106998"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5493270"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21-neoforge",
          "version": {
            "requires": "19.5.0.31"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-neoforge",
          "version": {
            "requires": "1.1.10+1.21"
          }
        }
      ],
      "files": [
        {
          "name": "TomsTradingNetwork-121-0.3.3.jar",
          "url": "TomsTradingNetwork-121-0.3.3.jar",
          "size": 269077,
          "sha512": "ef230cc0f1dd2365fa6908d4fb0461591b201feda785a09369650aec15c2b81d222097244379651a18fe59ce46f96df351725c2f26c9f5932e1f51782d331f20",
          "sha256": "1bfce1ac9036cd45668c473afee63f7548b64b31430125783c7b16dca5cb7cce",
          "sha1": "bd83a79cbfe52a7d969430fc3ac2cfdaf9115640",
          "md5": "d48f08297f6340cc055c5c8272cb01b6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TomsTradingNetwork-121-0.3.3-sources.jar",
          "url": "TomsTradingNetwork-121-0.3.3-sources.jar",
          "size": 198699,
          "sha512": "7dba787121d97c3fabfb2375b683cb5c3fa93e825ee02a593f80e46e874e0b4c9fa216b465aa517f1d15d01e0952a627a3b756776d1c2f8afef38cb649afffb7",
          "sha256": "9c37bd30b4921dfb65bbbb63439ff90b82efd151fbf04811d3935cd0cd49a9f1",
          "sha1": "db639f6ef20d48b861e5e1beba9f3699a0df89b7",
          "md5": "15a26e70bc01eb3af1d75b439109478a"
        }
      ]
    }
  ]
}
