{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.toms_storage",
    "module": "TomsStorage-26.1",
    "version": "2.10.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "TomsStorage-26.1-2.10.2.jar",
          "url": "TomsStorage-26.1-2.10.2.jar",
          "size": 861270,
          "sha512": "6289518633a834bc85b300cbde94960f567902d9b8ffd523c8930e87cf686b97555d43dd492cce112f2a91166a8cc98a34d72f4fe8e93908b79802d0866f690a",
          "sha256": "fdd0e44e124c7d745c26ca8e96b79bdb828ee98090c1fb831b07c9ab06525795",
          "sha1": "337554cf35c35ae783528e972b2362988fe0d609",
          "md5": "8ffd9f4b0b2af9c926cc88527477796e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "7817285"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-neoforge",
          "version": {
            "requires": "21.11.814"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-neoforge",
          "version": {
            "requires": "18.0.145"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-neoforge",
          "version": {
            "requires": "16.1.4"
          }
        },
        {
          "group": "curse.maven",
          "module": "polymorph-388800",
          "version": {
            "requires": "5995380"
          }
        },
        {
          "group": "curse.maven",
          "module": "the-one-probe-245211",
          "version": {
            "requires": "5502323"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-26.1.2-neoforge",
          "version": {
            "requires": "29.29.0.77"
          }
        },
        {
          "group": "top.theillusivec4.curios",
          "module": "curios-neoforge",
          "version": {
            "requires": "11.0.1+1.21.5"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-neoforge",
          "version": {
            "requires": "1.1.7+1.21"
          }
        }
      ],
      "files": [
        {
          "name": "TomsStorage-26.1-2.10.2.jar",
          "url": "TomsStorage-26.1-2.10.2.jar",
          "size": 861270,
          "sha512": "6289518633a834bc85b300cbde94960f567902d9b8ffd523c8930e87cf686b97555d43dd492cce112f2a91166a8cc98a34d72f4fe8e93908b79802d0866f690a",
          "sha256": "fdd0e44e124c7d745c26ca8e96b79bdb828ee98090c1fb831b07c9ab06525795",
          "sha1": "337554cf35c35ae783528e972b2362988fe0d609",
          "md5": "8ffd9f4b0b2af9c926cc88527477796e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TomsStorage-26.1-2.10.2-sources.jar",
          "url": "TomsStorage-26.1-2.10.2-sources.jar",
          "size": 553607,
          "sha512": "df618ebf0b07a1a1d116e4ab076da27b7fdcbff3debdc0dd20cd647b5e63e4745dd3af1ae48c6b10f24a422b387d3d2078ae38728cd1c86d3d7978c85e1788f4",
          "sha256": "11ddfdf43498c6ab0c51f54926bd02a8329626688a0d79b473d070931fa94ff6",
          "sha1": "37d5c99536f917538cc5651349b61cee8e7a807c",
          "md5": "52df66f42ae67584c977fc5ff9715816"
        }
      ]
    },
    {
      "name": "accessTransformerElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "TomsStorage-26.1-2.10.2-access-transformer.cfg",
          "url": "TomsStorage-26.1-2.10.2-access-transformer.cfg",
          "size": 580,
          "sha512": "54fdf56d9dfdaf8bf7935087c6b0b3ced9483c38f324cde64967381ae30892c408f87f00725c13329474d2d1a58ccd4dd7f2fafb1071037842aa0bf6160c75d3",
          "sha256": "654f2b47449578b9ba65586cd2c1b89f128c00ec3c035436dbc714badc6c289a",
          "sha1": "82eb657c2ab86d84fd8f198f4eb64e4df564e315",
          "md5": "1819b5c4f40faba330a37ed08e2432fd"
        }
      ]
    }
  ]
}
