{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.toms_storage",
    "module": "TomsStorage-1.21.4",
    "version": "2.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "TomsStorage-1.21.4-2.1.3.jar",
          "url": "TomsStorage-1.21.4-2.1.3.jar",
          "size": 823487,
          "sha512": "67a4bd0af2da922106a413cda245dc2d1b1c6bace1bd846860e8ee2c05ba700e5972c10a2b94a4d0073213a9ca37bc5d4912086beb6425af5074e47e52fe582a",
          "sha256": "c6fcc27a62566d51c9e112353455ccf2a64e8a45569ce8f6a01bc08b1abe36e3",
          "sha1": "3c021c870a6deb2efffcc7ce50fcb0771687b4ab",
          "md5": "4f2f829488eb8591f467abd39c2a4303"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-neoforge",
          "version": {
            "requires": "14.0.688"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-neoforge",
          "version": {
            "requires": "13.0.121"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-neoforge",
          "version": {
            "requires": "11.0.9"
          }
        },
        {
          "group": "curse.maven",
          "module": "polymorph-388800",
          "version": {
            "requires": "5480541"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5529595"
          }
        },
        {
          "group": "curse.maven",
          "module": "the-one-probe-245211",
          "version": {
            "requires": "5502323"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.19.0.219"
          }
        },
        {
          "group": "top.theillusivec4.curios",
          "module": "curios-neoforge",
          "version": {
            "requires": "8.0.0-beta.6+1.20.6"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-neoforge",
          "version": {
            "requires": "1.1.7+1.21"
          }
        }
      ],
      "files": [
        {
          "name": "TomsStorage-1.21.4-2.1.3.jar",
          "url": "TomsStorage-1.21.4-2.1.3.jar",
          "size": 823487,
          "sha512": "67a4bd0af2da922106a413cda245dc2d1b1c6bace1bd846860e8ee2c05ba700e5972c10a2b94a4d0073213a9ca37bc5d4912086beb6425af5074e47e52fe582a",
          "sha256": "c6fcc27a62566d51c9e112353455ccf2a64e8a45569ce8f6a01bc08b1abe36e3",
          "sha1": "3c021c870a6deb2efffcc7ce50fcb0771687b4ab",
          "md5": "4f2f829488eb8591f467abd39c2a4303"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TomsStorage-1.21.4-2.1.3-sources.jar",
          "url": "TomsStorage-1.21.4-2.1.3-sources.jar",
          "size": 530532,
          "sha512": "6f196860366f4d9c223c098380f95675bdc10dbf96ead5fb7e298e1204572cba35b228e7cf1ead840eaa4ae6c372e0427a34e87c7f97cbcfe97cf7db634a5ec2",
          "sha256": "8d208acedb96f8c71e258eae00a4c84698f0dd9961a8aefbea071c203cc6917a",
          "sha1": "d201fa0199806e2559a275ccd81e6be79826951c",
          "md5": "78112a26ca1d73c0efeb7622b197137e"
        }
      ]
    }
  ]
}
