{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.createstockbridge",
    "module": "CreateStockBridge-1.21",
    "version": "0.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "CreateStockBridge-1.21-0.1.6.jar",
          "url": "CreateStockBridge-1.21-0.1.6.jar",
          "size": 173051,
          "sha512": "bdc3247e2f361018eb15dbd1008a672f37830066cafae9ddb99c75ca33e0ae962d1292a7c4706adb06872fb4687b2ad9046aa6f5d2b5127359b6bd517201d713",
          "sha256": "505d4f65b8692d3fb66684f7389fd8b80f4710194f0ea8822e942888c8ab9e52",
          "sha1": "3ba1d0ca05211bfd28a03ce6492f9e66d08e430a",
          "md5": "03c52d9555f07fb0c42f3423d15d0378"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "the-one-probe-245211",
          "version": {
            "requires": "5502323"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5529595"
          }
        },
        {
          "group": "curse.maven",
          "module": "refined-storage-243076",
          "version": {
            "requires": "6358597"
          }
        },
        {
          "group": "curse.maven",
          "module": "applied-energistics-2-223794",
          "version": {
            "requires": "6225422"
          }
        },
        {
          "group": "curse.maven",
          "module": "guideme-1173950",
          "version": {
            "requires": "6331224"
          }
        },
        {
          "group": "curse.maven",
          "module": "ae2-jei-integration-1074338",
          "version": {
            "requires": "5748513"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.6-98"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.21.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.56"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.21.0.247"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "CreateStockBridge-1.21-0.1.6.jar",
          "url": "CreateStockBridge-1.21-0.1.6.jar",
          "size": 173051,
          "sha512": "bdc3247e2f361018eb15dbd1008a672f37830066cafae9ddb99c75ca33e0ae962d1292a7c4706adb06872fb4687b2ad9046aa6f5d2b5127359b6bd517201d713",
          "sha256": "505d4f65b8692d3fb66684f7389fd8b80f4710194f0ea8822e942888c8ab9e52",
          "sha1": "3ba1d0ca05211bfd28a03ce6492f9e66d08e430a",
          "md5": "03c52d9555f07fb0c42f3423d15d0378"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "CreateStockBridge-1.21-0.1.6-sources.jar",
          "url": "CreateStockBridge-1.21-0.1.6-sources.jar",
          "size": 124589,
          "sha512": "05c371cafa44c75b5d8f1bb50b40d68cb3a97ed79dbf6a1fad7b88edcceb5a72ff7fce9a4745a392a68c3da611393899dca18f34f54fc18d775ce8cfbc9740e6",
          "sha256": "7c1ca19c6cc6f251d75116c3118d1a44a404cf44e8c8169469728c00197a000d",
          "sha1": "d2076ebbb1c79eb84962ee234e6cf53914c3dade",
          "md5": "56ef8c18057b5e8f5f778d1970137e90"
        }
      ]
    }
  ]
}
