{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.toms_trading",
    "module": "TomsTradingNetwork-1202",
    "version": "0.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "TomsTradingNetwork-1202-0.2.6.jar",
          "url": "TomsTradingNetwork-1202-0.2.6.jar",
          "size": 200680,
          "sha512": "ebcb26a01e45a62efe4ccc0e364853c8c4e7079f28d7779c4d0a35d37b7def0e1464156dad8967a822f5aa4d0276f8bc8ede29b9901ea86f27e8035168c7ee73",
          "sha256": "e008f178fb138b7456e02bc8c64849fce831db428db71dda5380e46ee178dd22",
          "sha1": "f0c19d86d1e81f79eb7afc16e639bb3c2b198638",
          "md5": "8a3c3f9daa1f1945d0bd09734910ce88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TomsTradingNetwork-1202-0.2.6.jar",
          "url": "TomsTradingNetwork-1202-0.2.6.jar",
          "size": 200680,
          "sha512": "ebcb26a01e45a62efe4ccc0e364853c8c4e7079f28d7779c4d0a35d37b7def0e1464156dad8967a822f5aa4d0276f8bc8ede29b9901ea86f27e8035168c7ee73",
          "sha256": "e008f178fb138b7456e02bc8c64849fce831db428db71dda5380e46ee178dd22",
          "sha1": "f0c19d86d1e81f79eb7afc16e639bb3c2b198638",
          "md5": "8a3c3f9daa1f1945d0bd09734910ce88"
        }
      ]
    }
  ]
}
