{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.toms_trading",
    "module": "TomsTradingNetworkFabric-119",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.19.2-common-api",
          "version": {
            "requires": "11.6.0.1013"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.19.2-fabric-api",
          "version": {
            "requires": "11.6.0.1013"
          }
        }
      ],
      "files": [
        {
          "name": "TomsTradingNetworkFabric-119-0.2.1.jar",
          "url": "TomsTradingNetworkFabric-119-0.2.1.jar",
          "size": 224297,
          "sha512": "f8f7c236acb2b80e2058817c258809ce251abfdb49ed82727642bf98c753495a841b1575b9c104ea95ff81ad6c63285c4cb19c76ae9c642040e1cba5276cb4ca",
          "sha256": "a6adfd244f97f429a74ae6113f1c767fbc41bdbf49b2340a9e8b7fb8810ff38e",
          "sha1": "9ec114fbe3fef81059e9967d4e1b3ad7ba8439d1",
          "md5": "646b9df6bc47fd862942a1a48e163d61"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.14"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "forge-config-api-port-fabric-547434",
          "version": {
            "requires": "4401535"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "4.0.6"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "6.2.43"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi",
          "version": {
            "requires": "0.7.3+1.19.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "4328558"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "9.1.562"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "dev.architectury",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.19.2-fabric",
          "version": {
            "requires": "11.6.0.1013"
          }
        }
      ],
      "files": [
        {
          "name": "TomsTradingNetworkFabric-119-0.2.1.jar",
          "url": "TomsTradingNetworkFabric-119-0.2.1.jar",
          "size": 224297,
          "sha512": "f8f7c236acb2b80e2058817c258809ce251abfdb49ed82727642bf98c753495a841b1575b9c104ea95ff81ad6c63285c4cb19c76ae9c642040e1cba5276cb4ca",
          "sha256": "a6adfd244f97f429a74ae6113f1c767fbc41bdbf49b2340a9e8b7fb8810ff38e",
          "sha1": "9ec114fbe3fef81059e9967d4e1b3ad7ba8439d1",
          "md5": "646b9df6bc47fd862942a1a48e163d61"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TomsTradingNetworkFabric-119-0.2.1-sources.jar",
          "url": "TomsTradingNetworkFabric-119-0.2.1-sources.jar",
          "size": 164269,
          "sha512": "61f9a8bc5d1460349c2ccc629f671954541671ccbb59ae5c6d3c9fb6c4587bdb9cb4c982d1c065ed4dbfa278663960088d0ee1f1b7f76eecb57a2b465fec1376",
          "sha256": "651a6f77af8c0c891c3ea444167dd410da10d42a4d98e1cb98e3ed7495d5b972",
          "sha1": "1ed1207dfb6aeaa4841f74389385b39aa45bc430",
          "md5": "0c1738d1d127a8ae9499b0e06cd0dd92"
        }
      ]
    }
  ]
}
