{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.toms_storage",
    "module": "TomsStorage-121",
    "version": "2.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "TomsStorage-121-2.4.2.jar",
          "url": "TomsStorage-121-2.4.2.jar",
          "size": 856803,
          "sha512": "53db61b4486616b3a78dfff83b58f9424dd9bf525ea3db4e444ff0403fb70aa9ab7fc097dff2f49665e480bce936b32be76b3051a5aff217898b2b94d846d30b",
          "sha256": "a703e28391b914298223a515238c8729007606f2f967a83b65b8d5cb39e0789d",
          "sha1": "592af3bc4768c804c4929af16961ca2a1a916942",
          "md5": "60be115121d183a559ecdee2b35dae3b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-neoforge",
          "version": {
            "requires": "16.0.799"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-neoforge",
          "version": {
            "requires": "15.0.140"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-neoforge",
          "version": {
            "requires": "13.0.8"
          }
        },
        {
          "group": "curse.maven",
          "module": "polymorph-388800",
          "version": {
            "requires": "5995380"
          }
        },
        {
          "group": "curse.maven",
          "module": "the-one-probe-245211",
          "version": {
            "requires": "5502323"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5529595"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.22.0.315"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-neoforge",
          "version": {
            "requires": "1.1.19+1.21.1"
          }
        },
        {
          "group": "top.theillusivec4.curios",
          "module": "curios-neoforge",
          "version": {
            "requires": "9.4.0+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "TomsStorage-121-2.4.2.jar",
          "url": "TomsStorage-121-2.4.2.jar",
          "size": 856803,
          "sha512": "53db61b4486616b3a78dfff83b58f9424dd9bf525ea3db4e444ff0403fb70aa9ab7fc097dff2f49665e480bce936b32be76b3051a5aff217898b2b94d846d30b",
          "sha256": "a703e28391b914298223a515238c8729007606f2f967a83b65b8d5cb39e0789d",
          "sha1": "592af3bc4768c804c4929af16961ca2a1a916942",
          "md5": "60be115121d183a559ecdee2b35dae3b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "TomsStorage-121-2.4.2-sources.jar",
          "url": "TomsStorage-121-2.4.2-sources.jar",
          "size": 553400,
          "sha512": "edce1f5adedff1f775d6de847abdfc729785bba6b526b07fa178d88c21bfab501ea0a267ca890c6fb0ecf9c8974c693cf4cda17a1efc128492394c7e53a33c53",
          "sha256": "ff58ad7f3dfb14f7c4619cd10d3c237228dca54944e3a9d3a834494a8fbbea51",
          "sha1": "e1031ed2ed013b9d081fcad3d3a80dc915b1d267",
          "md5": "b1c0d0975e0c21d757dc00e4ba695799"
        }
      ]
    }
  ]
}
