{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tom5454.createstockbridge",
    "module": "CreateStockBridge-1.21",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "CreateStockBridge-1.21-0.1.2.jar",
          "url": "CreateStockBridge-1.21-0.1.2.jar",
          "size": 171035,
          "sha512": "35879d936a96c7cdb5879f78c3746628a71637d01dcd6bd939963e62f3588ad0857dda0b34e209a02951d570621a6b8cafa1176459bff4089cd80e1285ebbeb0",
          "sha256": "853dce1d78ce3b0c0e4ef7fa061196ccf721263aee9049ddd9a6b2c755645fd9",
          "sha1": "878aa9476780e48bed9b97a6663ea3f1249d6768",
          "md5": "d12ed611322cff6ffd2f680b9090c012"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "the-one-probe-245211",
          "version": {
            "requires": "5502323"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5529595"
          }
        },
        {
          "group": "curse.maven",
          "module": "refined-storage-243076",
          "version": {
            "requires": "6358597"
          }
        },
        {
          "group": "curse.maven",
          "module": "applied-energistics-2-223794",
          "version": {
            "requires": "6225422"
          }
        },
        {
          "group": "curse.maven",
          "module": "guideme-1173950",
          "version": {
            "requires": "6331224"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.21.1",
          "version": {
            "requires": "6.0.4-53"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.21.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-NeoForge-1.21.1",
          "version": {
            "requires": "1.0.44"
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.21-1.3.0+62"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.21.1-neoforge",
          "version": {
            "requires": "19.21.0.247"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-neoforge-1.21.1",
          "version": {
            "requires": "1.0.1-11"
          }
        }
      ],
      "files": [
        {
          "name": "CreateStockBridge-1.21-0.1.2.jar",
          "url": "CreateStockBridge-1.21-0.1.2.jar",
          "size": 171035,
          "sha512": "35879d936a96c7cdb5879f78c3746628a71637d01dcd6bd939963e62f3588ad0857dda0b34e209a02951d570621a6b8cafa1176459bff4089cd80e1285ebbeb0",
          "sha256": "853dce1d78ce3b0c0e4ef7fa061196ccf721263aee9049ddd9a6b2c755645fd9",
          "sha1": "878aa9476780e48bed9b97a6663ea3f1249d6768",
          "md5": "d12ed611322cff6ffd2f680b9090c012"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "CreateStockBridge-1.21-0.1.2-sources.jar",
          "url": "CreateStockBridge-1.21-0.1.2-sources.jar",
          "size": 124053,
          "sha512": "147dcc6eef061dc0deadf5d487004007130b51e595682fb9577efcf35da16a2916b18c57109f2f787309f6356ab2e311c06e2dcf1a2eefc0b52b2260e940725f",
          "sha256": "f1c4d41a42d17e79fc27150afc0aff8a177d5de845bc4c9d4df0f73d99d87dd8",
          "sha1": "9f81d1204b8f7fe0c793d2bef1352ab3b36f2fb0",
          "md5": "88f491c504430b2438cf092471eb363c"
        }
      ]
    }
  ]
}
